/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-19 15:05:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Jo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1639549998000L));
    _jspx_dependants.put("jar:file:/C:/Bcle/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ViewPage/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <title>Registration Form</title>\r\n");
      out.write("    <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.register{\r\n");
      out.write("    background: -webkit-linear-gradient(left, #3931af, #00c6ff);\r\n");
      out.write("    margin-top: 3%;\r\n");
      out.write("    padding: 3%;\r\n");
      out.write("}\r\n");
      out.write(".register-left{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin-top: 4%;\r\n");
      out.write("}\r\n");
      out.write(".register-left input{\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 1.5rem;\r\n");
      out.write("    padding: 2%;\r\n");
      out.write("    width: 60%;\r\n");
      out.write("    background: #f8f9fa;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #383d41;\r\n");
      out.write("    margin-top: 30%;\r\n");
      out.write("    margin-bottom: 3%;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".register-right{\r\n");
      out.write("    background: #f8f9fa;\r\n");
      out.write("    border-top-left-radius: 10% 50%;\r\n");
      out.write("    border-bottom-left-radius: 10% 50%;\r\n");
      out.write("}\r\n");
      out.write(".register-left img{\r\n");
      out.write("    margin-top: 15%;\r\n");
      out.write("    margin-bottom: 5%;\r\n");
      out.write("    width: 25%;\r\n");
      out.write("    -webkit-animation: mover 2s infinite  alternate;\r\n");
      out.write("    animation: mover 1s infinite  alternate;\r\n");
      out.write("}\r\n");
      out.write("@-webkit-keyframes mover {\r\n");
      out.write("    0% { transform: translateY(0); }\r\n");
      out.write("    100% { transform: translateY(-20px); }\r\n");
      out.write("}\r\n");
      out.write("@keyframes mover {\r\n");
      out.write("    0% { transform: translateY(0); }\r\n");
      out.write("    100% { transform: translateY(-20px); }\r\n");
      out.write("}\r\n");
      out.write(".register-left p{\r\n");
      out.write("    font-weight: lighter;\r\n");
      out.write("    padding: 12%;\r\n");
      out.write("    margin-top: -9%;\r\n");
      out.write("}\r\n");
      out.write(".register .register-form{\r\n");
      out.write("    padding: 10%;\r\n");
      out.write("    margin-top: 10%;\r\n");
      out.write("}\r\n");
      out.write(".btnRegister{\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin-top: 10%;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 1.5rem;\r\n");
      out.write("    padding: 2%;\r\n");
      out.write("    background: #0062cc;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    width: 50%;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".register .nav-tabs{\r\n");
      out.write("    margin-top: 3%;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background: #0062cc;\r\n");
      out.write("    border-radius: 1.5rem;\r\n");
      out.write("    width: 28%;\r\n");
      out.write("    float: right;\r\n");
      out.write("}\r\n");
      out.write(".register .nav-tabs .nav-link{\r\n");
      out.write("    padding: 2%;\r\n");
      out.write("    height: 34px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border-top-right-radius: 1.5rem;\r\n");
      out.write("    border-bottom-right-radius: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write(".register .nav-tabs .nav-link:hover{\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write(".register .nav-tabs .nav-link.active{\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    color: #0062cc;\r\n");
      out.write("    border: 2px solid #0062cc;\r\n");
      out.write("    border-top-left-radius: 1.5rem;\r\n");
      out.write("    border-bottom-left-radius: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write(".register-heading{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 8%;\r\n");
      out.write("    margin-bottom: -15%;\r\n");
      out.write("    color: #495057;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container register\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-9 register-right\">\r\n");
      out.write("                        <ul class=\"nav nav-tabs nav-justified\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link active\" id=\"home-tab\" data-toggle=\"tab\" href=\"#home\" role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">Employee</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\" aria-controls=\"profile\" aria-selected=\"false\">Hirer</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("                            <div class=\"tab-pane fade show active\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("                                <h3 class=\"register-heading\">Apply as a Employee</h3>\r\n");
      out.write("                                <div class=\"row register-form\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"First Name *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"Last Name *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" placeholder=\"Password *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control\"  placeholder=\"Confirm Password *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"maxl\">\r\n");
      out.write("                                                <label class=\"radio inline\"> \r\n");
      out.write("                                                    <input type=\"radio\" name=\"gender\" value=\"male\" checked>\r\n");
      out.write("                                                    <span> Male </span> \r\n");
      out.write("                                                </label>\r\n");
      out.write("                                                <label class=\"radio inline\"> \r\n");
      out.write("                                                    <input type=\"radio\" name=\"gender\" value=\"female\">\r\n");
      out.write("                                                    <span>Female </span> \r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"email\" class=\"form-control\" placeholder=\"Your Email *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" minlength=\"10\" maxlength=\"10\" name=\"txtEmpPhone\" class=\"form-control\" placeholder=\"Your Phone *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <select class=\"form-control\">\r\n");
      out.write("                                                <option class=\"hidden\"  selected disabled>Please select your Sequrity Question</option>\r\n");
      out.write("                                                <option>What is your Birthdate?</option>\r\n");
      out.write("                                                <option>What is Your old Phone Number</option>\r\n");
      out.write("                                                <option>What is your Pet Name?</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"Enter Your Answer *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <input type=\"submit\" class=\"btnRegister\"  value=\"Register\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane fade show\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("                                <h3  class=\"register-heading\">Apply as a Hirer</h3>\r\n");
      out.write("                                <div class=\"row register-form\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"First Name *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"Last Name *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"email\" class=\"form-control\" placeholder=\"Email *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" maxlength=\"10\" minlength=\"10\" class=\"form-control\" placeholder=\"Phone *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" placeholder=\"Password *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" placeholder=\"Confirm Password *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <select class=\"form-control\">\r\n");
      out.write("                                                <option class=\"hidden\"  selected disabled>Please select your Sequrity Question</option>\r\n");
      out.write("                                                <option>What is your Birthdate?</option>\r\n");
      out.write("                                                <option>What is Your old Phone Number</option>\r\n");
      out.write("                                                <option>What is your Pet Name?</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"`Answer *\" value=\"\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <input type=\"submit\" class=\"btnRegister\"  value=\"Register\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
