SELECT USER
FROM DUAL;
--==>> TEAMONE


--1. 참조키 O개 OR 기본정보


--○ 관리자  
CREATE TABLE ADMIN (
	ADMIN_ID	VARCHAR2(20),
	PWD	    VARCHAR2(16) NOT NULL,
	NAME	VARCHAR2(40) NOT NULL,
	EMAIL	VARCHAR2(100) NOT NULL,
    
    CONSTRAINT PK_ADMIN_ADMIN_ID PRIMARY KEY(ADMIN_ID)
);


--○ 지역 - 시
CREATE TABLE REGION_L 
( REGION_L_ID   VARCHAR2(20)	    
, CITY          VARCHAR2(20)	        NOT NULL
, CONSTRAINT REGION_L_REGION_L_ID_PK PRIMARY KEY(REGION_L_ID)
);


--○ 지역-군/구	REGION_S
CREATE TABLE REGION_S (
	REGION_S_ID	    VARCHAR2(20)	
	,REGION_L_ID	VARCHAR2(20)	NOT NULL
	,LOCAL	        VARCHAR2(20)	NOT NULL
    ,CONSTRAINT REGION_S_REGION_S_ID_PK PRIMARY KEY(REGION_S_ID)
    ,CONSTRAINT REGION_S_REGION_L_ID_FK FOREIGN KEY(REGION_L_ID)
                REFERENCES REGION_L(REGION_L_ID)
);


--○ 지역 제한	LIMIT_REGION
CREATE TABLE LIMIT_REGION (
	LIMIT_ID	    VARCHAR2(20)	
	,REGION_S_ID	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT LIMIT_REGION_LIMIT_ID_PK PRIMARY KEY(LIMIT_ID)
    ,CONSTRAINT LIMIT_REGION_REGION_S_ID_FK FOREIGN KEY(REGION_S_ID)
                REFERENCES REGION_S(REGION_S_ID)
);

--○ 카테고리 대분류
CREATE TABLE CATEGORY_L
( CATEGORY_L_ID     VARCHAR2(20)   
, L_CAT             VARCHAR2(20)   NOT NULL
, CONSTRAINT CATEGORY_L_CATEGORY_L_ID_PK PRIMARY KEY(CATEGORY_L_ID)
);


--○ 카테고리 소분류
CREATE TABLE CATEGORY_S 
( CATEGORY_S_ID     VARCHAR2(20)  
, CATEGORY_L_ID     VARCHAR2(20)   NOT NULL
, S_CAT             VARCHAR2(50)   NOT NULL
, CONSTRAINT CATEGORY_S_CATEGORY_S_ID_PK PRIMARY KEY(CATEGORY_S_ID)
, CONSTRAINT CATEGORY_S_CATEGORY_L_ID_FK FOREIGN KEY(CATEGORY_L_ID) REFERENCES CATEGORY_L(CATEGORY_L_ID)
);


--○ 직위
CREATE TABLE POSITION
( POSITION_ID   VARCHAR2(20)    	
, NAME          VARCHAR2(20)    NOT	NULL
, CONSTRAINT POSITION_POSITION_ID PRIMARY KEY(POSITION_ID)
);


--○ 상태(유령,휴면,종료,비활성화)	STATUS
CREATE TABLE STATUS (
	STATUS_ID	VARCHAR2(20)	
	,NAME	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT STATUS_STATUS_ID_PK PRIMARY KEY(STATUS_ID)
);


--○ 반려 이유 - 거절인지 시간초과인지	RETURN_REASON
CREATE TABLE RETURN_REASON (
	REASON_ID	VARCHAR2(20)	
	,REASON 	VARCHAR2(500)	NOT NULL
    ,CONSTRAINT RETURN_REASON_REASON_ID_PK PRIMARY KEY(REASON_ID)
);


--○ 투표 종류
CREATE TABLE VOTE_TYPE 
( VOTE_ID   VARCHAR2(20)   
, TYPE      VARCHAR2(20)   NOT NULL
, CONSTRAINT VOTE_TYPE_VOTE_ID_PK PRIMARY KEY(VOTE_ID)
);

--○ 찬반
CREATE TABLE P_A_C
( PAC_ID    VARCHAR2(20)    
, PAC       VARCHAR2(20)    NOT	NULL
, CONSTRAINT P_A_C_PAC_ID_PK  PRIMARY KEY(PAC_ID)
);


--○ 평가항목
CREATE TABLE EVAL_ITEM 
( EVAL_ID   VARCHAR2(20)   
, CONTENT   VARCHAR(100)   NOT NULL
, CONSTRAINT EVAL_ITEM_EVAL_ID_PK PRIMARY KEY(EVAL_ID)
);


--○ 모임종류	  BEE_TYPE	
CREATE TABLE BEE_TYPE (
	TYPE_ID	    VARCHAR2(20)	
	,TYPE	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT BEE_TYPE_TYPE_ID_PK PRIMARY KEY(TYPE_ID)
);


--○ 처리 사유
CREATE TABLE HANDLE_REASON
( REASON_ID VARCHAR2(20)    
, REASON    VARCHAR2(500)	NOT NULL
, CONSTRAINT HANDLE_REASON_REASON_ID_PK PRIMARY KEY(REASON_ID)
);


--○ 삭제 사유	DEL_REASON	
CREATE TABLE DEL_REASON (
	REASON_ID	VARCHAR2(20)	
	,REASON	VARCHAR2(500)	NOT NULL
    ,CONSTRAINT DEL_REASON_REASON_ID_PK PRIMARY KEY(REASON_ID)
);

 
--○ 닉네임 색상    
CREATE TABLE COLOR (
	COLOR_ID VARCHAR2(20),
	NAME VARCHAR2(40) NOT NULL,
    
    CONSTRAINT PK_COLOR_COLOR_ID PRIMARY KEY(COLOR_ID)
);

 
--○ 닉네임 동물  
CREATE TABLE ANIMAL (
	ANIMAL_ID VARCHAR2(20),
	NAME	  VARCHAR2(40) NOT NULL,
    
    CONSTRAINT PK_ANIMAL_ANIMAL_ID PRIMARY KEY(ANIMAL_ID)
);

 

--○ 회원
CREATE TABLE MEMBER 
( MID	        VARCHAR2(20)
, BDATE	        DATE	        DEFAULT SYSDATE
, LOGIN_DATE	DATE	        DEFAULT SYSDATE
, CATEGORY_S_ID	VARCHAR2(20)	    NOT NULL
, CONSTRAINT MEMBER_MID_PK PRIMARY KEY(MID)
, CONSTRAINT MEMBER_CATEGORY_S_ID_FK FOREIGN KEY(CATEGORY_S_ID) REFERENCES CATEGORY_S(CATEGORY_S_ID)
);


--○ 회원 정보
CREATE TABLE MEMBERINFO 
( ID           VARCHAR2(20)   
, NAME           VARCHAR2(40)    NOT NULL
, SSN           CHAR(13)       NOT NULL
, EMAIL           VARCHAR2(100)   NOT NULL
, TEL           VARCHAR2(20)    NOT NULL
, PWD           VARCHAR2(16)   NOT NULL
, NICKNAME       VARCHAR2(50)   NOT NULL
, URL           VARCHAR2(500)   NULL
, REGION_S_ID   VARCHAR2(20)   NOT NULL
, MID           VARCHAR2(20)   NOT NULL
, CONSTRAINT MEMBERINFO_ID_PK PRIMARY KEY(ID)
, CONSTRAINT MEMBERINFO_REGION_S_ID_FK FOREIGN KEY(REGION_S_ID) REFERENCES REGION_S(REGION_S_ID)
, CONSTRAINT MEMBERINFO_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
, CONSTRAINT MEMBERINFO_SSN_UK UNIQUE(SSN);
, CONSTRAINT MEMBERINFO_EMAIL_UK UNIQUE(EMAIL);
, CONSTRAINT MEMBERINFO_NICKNAME_UK UNIQUE(NICKNAME);
);


--○ 탈퇴 회원
CREATE TABLE BACKUP_MEMBER 
( BACKUP_ID     VARCHAR2(20)   
, BDATE          DATE            DEFAULT SYSDATE 
, NAME          VARCHAR2(40)    NOT NULL
, SSN           CHAR(13)        NOT NULL
, EMAIL         VARCHAR2(100)   NOT NULL
, TEL           VARCHAR2(20)    NOT NULL
, ID            VARCHAR2(20)    NOT NULL
, MID           VARCHAR2(20)    NOT NULL
);


-- 동아리 개설상태 테이블
CREATE TABLE OPENSTATUS
(
    OPENSTATUS_ID   VARCHAR2(20),
    STATUS          VARCHAR2(20)    NOT NULL
    ,CONSTRAINT OPENSTATUS_OPENSTATUS_ID_PK PRIMARY KEY(OPENSTATUS_ID)
);


CREATE TABLE LIMIT_AGE
(
 AGELIMIT_ID VARCHAR2(20)
 ,OX CHAR(2)NOT NULL
 ,CONSTRAINT LIMIT_AGE_AGELIMIT_ID_PK PRIMARY KEY(AGELIMIT_ID)
);


CREATE TABLE LIMIT_REGION
(
 LIMIT_ID VARCHAR2(20)
 ,OX CHAR(2)NOT NULL
 ,CONSTRAINT LIMIT_REGION_LIMIT_ID_PK PRIMARY KEY(LIMIT_ID)
);

-- 동아리 2 
CREATE TABLE CLUB (
   CID               VARCHAR2(20),
   MAX               NUMBER(3) NOT NULL ,
   PREOPENDATE     DATE    DEFAULT SYSDATE, --가개설날짜
   BDATE           DATE,                    -- 정식개설날짜
   CONTENT           VARCHAR2(500),
   CATEGORY_S_ID   VARCHAR2(20)   NOT NULL,
   REGION_S_ID       VARCHAR2(20)   NOT NULL,
   MID               VARCHAR2(20) NOT NULL,
   URL               VARCHAR2(200),
   LIMIT_ID       VARCHAR2(20) NOT NULL,
   AGELIMIT_ID    VARCHAR2(20) NOT NULL,
   TITLE          VARCHAR2(100) NOT NULL,
    
    
    CONSTRAINT PK_CLUB_CID PRIMARY KEY(CID),
    CONSTRAINT FK_CLUB_CATEGORY_S_ID FOREIGN KEY(CATEGORY_S_ID) REFERENCES CATEGORY_S(CATEGORY_S_ID),
    CONSTRAINT FK_CLUB_REGION_S_ID FOREIGN KEY(REGION_S_ID) REFERENCES REGION_S(REGION_S_ID),
    CONSTRAINT FK_CLUB_MID FOREIGN KEY(MID) REFERENCES MEMBER(MID),
    CONSTRAINT FK_CLUB_AGELIMIT_ID FOREIGN KEY(AGELIMIT_ID) REFERENCES LIMIT_AGE(AGELIMIT_ID),
    CONSTRAINT FK_CLUB_LIMIT_ID FOREIGN KEY(LIMIT_ID) REFERENCES LIMIT_REGION(LIMIT_ID)
);


--○ 동아리 탈퇴(DROP_CLUB)
CREATE TABLE DROP_CLUB 
( DROPCLUB_ID	VARCHAR2(20)
, BDATE	        DATE	        DEFAULT SYSDATE
, CLUBMEM_ID	VARCHAR2(20)	    NOT NULL
, CONSTRAINT DROP_CLUB_DROPCLUB_ID_PK PRIMARY KEY(DROPCLUB_ID)
, CONSTRAINT DROP_CLUB_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);

--○ 관리자 동아리 삭제
CREATE TABLE CLUB_DEL (
	CD_ID	VARCHAR2(20)	,
	BDATE	DATE	DEFAULT SYSDATE,
	ADMIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(20)	NOT NULL,
	CID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_DEL_CD_ID PRIMARY KEY(CD_ID),
    CONSTRAINT FK_CLUB_DEL_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_CLUB_DEL_REASON_ID FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID),
    CONSTRAINT FK_CLUB_DEL_CID FOREIGN KEY(CID) REFERENCES CLUB(CID)
);

--○ 동아리신고접수	CLUB_REP
CREATE TABLE CLUB_REP (
	REP_ID	        VARCHAR2(20)	
	,CID	        VARCHAR2(20)	NOT NULL -- 동아리 코드
	,REP_DATE	    DATE	        DEFAULT SYSDATE --신고 접수 날짜
	,MID	        VARCHAR2(20)	NOT NULL -- 회원코드-신고자
	,R_REASON_ID	VARCHAR2(20)	NOT NULL --신고 접수 사유
	,PRO_DATE	    DATE	     -- 신고 처리 날짜
	,ADMIN_ID	    VARCHAR2(20) -- 처리한 관리자 ID
	,P_REASON_ID	VARCHAR2(20) -- 신고 처리 사유 
    ,CONSTRAINT CLUB_REP_REP_ID_PK PRIMARY KEY(REP_ID)
    ,CONSTRAINT CLUB_REP_CID_FK FOREIGN KEY(CID)
                REFERENCES CLUB(CID)
    ,CONSTRAINT CLUB_REP_MID_FK FOREIGN KEY(MID)
                REFERENCES MEMBER(MID)
    ,CONSTRAINT CLUB_REP_R_REASON_ID_FK FOREIGN KEY(R_REASON_ID)
                REFERENCES HANDLE_REASON(REASON_ID)
    ,CONSTRAINT CLUB_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT CLUB_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID)
                REFERENCES HANDLE_REASON(REASON_ID)
);

--○ 동아리 신고 기타 선택 시(접수)
CREATE TABLE CLUB_REP_ETC (
	R_ETC_ID	VARCHAR2(20),
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_REP_ETC_R_ETC_ID PRIMARY KEY(R_ETC_ID),
    CONSTRAINT FK_CLUB_REP_TEC_REP_ID FOREIGN KEY(REP_ID) REFERENCES CLUB_REP(REP_ID)
);

--○기타 선택 시(처리)  
CREATE TABLE CLUB_PRO_ETC (
	P_ETC_ID	VARCHAR2(20),
	CONTENT	VARCHAR2(500) NOT NULL,
	REP_ID	VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_CLUB_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT FK_CLUB_PRO_ETC_REP_ID FOREIGN KEY (REP_ID) REFERENCES CLUB_REP(REP_ID) 
);

--○ 추가 지역 선택
CREATE TABLE ADD_REGION
( ADD_REGION_ID 	VARCHAR2(20)	
, ID                VARCHAR2(20)	    NOT NULL
, REGION_S_ID       VARCHAR2(20)	    NOT NULL
, CONSTRAINT ADD_REGION_ADD_REGION_ID_PK PRIMARY KEY(ADD_REGION_ID)
, CONSTRAINT ADD_REGION_REGION_S_ID_FK FOREIGN KEY(REGION_S_ID) REFERENCES REGION_S(REGION_S_ID)
);


--○ 관리자- 동아리 상태 
CREATE TABLE CLUBSTATUS (

	CLUBSTATUS_ID       VARCHAR2(20),
	CID	                VARCHAR2(20) NOT NULL,
	STATUS_ID           VARCHAR2(20) NOT NULL,
	BDATE               DATE        DEFAULT SYSDATE,
    
    CONSTRAINT PK_CLUBSTATUS_CLUBSTATUS_ID PRIMARY KEY(CLUBSTATUS_ID),
    CONSTRAINT FK_CLUBSTATUS_CID FOREIGN KEY(CID) REFERENCES CLUB(CID),
    CONSTRAINT FK_CLUBSTATUS_STATUS_ID FOREIGN KEY(STATUS_ID) REFERENCES STATUS(STATUS_ID)
);

--○ 추가 카테고리 선택
CREATE TABLE ADD_CATEGORY
( ADD_CATEGORY_ID   VARCHAR2(20)
, MID               VARCHAR2(20)    	NOT NULL
, CATEGORY_S_ID	    VARCHAR2(20)	    NOT NULL

, CONSTRAINT ADD_CAT_ADD_CATEGORY_ID_PK PRIMARY KEY(ADD_CATEGORY_ID)
, CONSTRAINT ADD_CAT_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);


--○ 가입신청  
CREATE TABLE JOIN_CLUB (
	JOIN_ID	    VARCHAR2(20),
	CID	        VARCHAR2(20)	NOT NULL,
	MID	        VARCHAR2(20)	NOT NULL,
	BDATE	    DATE  DEFAULT SYSDATE,
    
    CONSTRAINT PK_JOIN_CLUB_JOIN_ID PRIMARY KEY(JOIN_ID),
    CONSTRAINT FK_JOIN_CLUB_CID FOREIGN KEY(CID) REFERENCES CLUB(CID),
    CONSTRAINT FK_JOIN_CLUB_MID FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);


--○ 가입 신청 반려 테이블 
CREATE TABLE JOIN_CLUB_RETURN (
	RETURN_ID	VARCHAR2(20)	,
	JOIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(200)	NOT NULL,
	BDATE	DATE	DEFAULT SYSDATE,
    
    CONSTRAINT JOIN_CLUB_RETURN_RETURN_ID_PK PRIMARY KEY(RETURN_ID),
    CONSTRAINT JOIN_CLUB_RETURN_JOIN_ID_FK FOREIGN KEY(JOIN_ID) REFERENCES JOIN_CLUB(JOIN_ID),
    CONSTRAINT JOIN_CLUB_RETURN_REASON_ID_FK FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID)
);


--○ 동아리 회원목록 
CREATE TABLE CLUBMEMBERLIST (
	CLUBMEM_ID	VARCHAR2(20),
	POSITION_ID	VARCHAR2(20) NOT NULL,
	JOIN_ID	VARCHAR2(20) NOT NULL,
	BDATE	DATE	DEFAULT SYSDATE,
    
    CONSTRAINT PK_CLUBMEMBERLIST_CLUBMEM_ID PRIMARY KEY(CLUBMEM_ID),
    CONSTRAINT FK_CLUBMEMBERLIST_POSITION_ID FOREIGN KEY(POSITION_ID) REFERENCES POSITION(POSITION_ID),
    CONSTRAINT FK_CLUBMEMBERLIST_JOIN_ID FOREIGN KEY(JOIN_ID) REFERENCES JOIN_CLUB(JOIN_ID)
);

 
--○ 동아리 강퇴회원목록  
CREATE TABLE BAN_MEM_LIST (
	BAN_MEM_ID	VARCHAR2(20)	,
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
	BDATE	DATE	DEFAULT SYSDATE,
    
    CONSTRAINT PK_BAM_MEM_LIST_BAN_MEM_ID PRIMARY KEY(BAN_MEM_ID),
    CONSTRAINT FK_BAM_MEM_LIST_CLUBMEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID) 
);

--○ 모임	 BEE    CHECK~> BEE_TIME은 등록일(SYSDATE) 이후로 설정 
CREATE TABLE BEE (
	BEE_ID  	    VARCHAR2(20)	
	,TYPE_ID	    VARCHAR2(20)	NOT NULL -- 모임 종류ID(정모/반짝)
	,TITLE	        VARCHAR2(100)	NOT NULL --모임 제목
    ,CLUBMEM_ID	    VARCHAR2(20)	NOT NULL -- 동아리 회원ID
    ,CONTENT	    VARCHAR2(4000)	
	,BEE_TIME	    DATE	        NOT NULL
	,WEATHER	    VARCHAR2(500)	
	,LOCATION	    VARCHAR2(500)	NOT NULL
	,MIN	        NUMBER(3)	    NOT NULL --최소 인원
	,MAX	        NUMBER(3)	             --최대 인원
	,FEE	        NUMBER	                 --참가비 
	,BDATE	        DATE	        DEFAULT SYSDATE --모임 등록일
    ,CONSTRAINT BEE_BEE_ID_PK PRIMARY KEY(BEE_ID)
    ,CONSTRAINT BEE_TYPE_ID_FK FOREIGN KEY(TYPE_ID)
                REFERENCES BEE_TYPE(TYPE_ID)
    ,CONSTRAINT BEE_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
    ,CONSTRAINT BEE_BEE_TIME_CK CHECK (BDATE < BEE_TIME)
);
--==>> Table BEE이(가) 생성되었습니다.


--○ 모임 관리자 삭제	 BEE_DEL
CREATE TABLE BEE_DEL (
	BD_ID	    VARCHAR2(20)	
	,BDATE	    DATE	        DEFAULT SYSDATE
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
	,REASON_ID	VARCHAR2(20)	NOT NULL
	,BEE_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT BEE_DEL_BD_ID_PK PRIMARY KEY(BD_ID)
    ,CONSTRAINT BEE_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT BEE_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
    ,CONSTRAINT BEE_DEL_BEE_ID_FK FOREIGN KEY(BEE_ID)
                REFERENCES BEE(BEE_ID)
);


--○ 모임 신청	BEE_REQ 
CREATE TABLE BEE_REQ (
	REQ_ID	    VARCHAR2(20)   
	,CLUBMEM_ID	VARCHAR2(20)	NOT NULL
	,BEE_ID	    VARCHAR2(20)	NOT NULL
    ,BDATE       DATE            DEFAULT SYSDATE
    ,CONSTRAINT BEE_REQ_REQ_ID_PK PRIMARY KEY(REQ_ID)
    ,CONSTRAINT BEE_REQ_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
    ,CONSTRAINT BEE_REQ_BEE_ID_FK FOREIGN KEY(BEE_ID)
                REFERENCES BEE(BEE_ID)
);


--○ 모임 불참 ABSENT
CREATE TABLE ABSENT (
    ABSENT_ID   VARCHAR2(20)
    ,REQ_ID      VARCHAR2(20)    NOT NULL
    ,BDATE        DATE            DEFAULT SYSDATE 
    ,CONSTRAINT ABSENT_ABSENT_ID_PK PRIMARY KEY(ABSENT_ID)
    ,CONSTRAINT ABSENT_REQ_ID_FK FOREIGN KEY(REQ_ID)
                REFERENCES BEE_REQ(REQ_ID)
);

--○ 모임 사진	BEE_PHOTO
CREATE TABLE BEE_PHOTO (
	PHOTO_ID	VARCHAR2(20)
	,BEE_ID	    VARCHAR2(20)	NOT NULL 
	,URL	    VARCHAR2(500)	NOT NULL --사진 경로
    ,CONSTRAINT BEE_PHOTO_PHOTO_ID_PK PRIMARY KEY(PHOTO_ID)
    ,CONSTRAINT BEE_PHOTO_BEE_ID_FK FOREIGN KEY(BEE_ID)
                REFERENCES BEE(BEE_ID)
);
--==>> Table BEE_PHOTO이(가) 생성되었습니다.


--○ 컨텐츠신고접수(동아리 - 정목/반짝)
CREATE TABLE BEE_REP 
( REP_ID        VARCHAR2(20)  
, BEE_ID        VARCHAR2(20)    NOT NULL            -- 모임 코드
, R_CLUBMEM_ID  VARCHAR2(20)    NOT NULL            -- 신고한 사람
, REP_DATE      DATE            DEFAULT SYSDATE     -- 신고 날짜
, R_REASON_ID   VARCHAR2(20)    NOT NULL            -- 신고 사유 코드
, P_REASON_ID   VARCHAR2(20)                        -- 처리 사유 코드
, PRO_DATE      DATE                                -- 처리 날짜
, ADMIN_ID      VARCHAR2(20)                        -- 관리자
, CONSTRAINT BEE_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT BEE_REP_BEE_ID_FK FOREIGN KEY(BEE_ID) REFERENCES BEE(BEE_ID)
, CONSTRAINT BEE_REP_R_CLUBMEM_ID_FK FOREIGN KEY(R_CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT BEE_REP_R_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT BEE_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT BEE_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);
--==>> Table BEE_REP이(가) 생성되었습니다.


--○ 정보/반짝 기타 (신고)	BEE_REP_ETC
CREATE TABLE BEE_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT BEE_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
    ,CONSTRAINT BEE_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES BEE_REP(REP_ID)
);
--==>> Table BEE_REP_ETC이(가) 생성되었습니다.

--○ 정보/반짝 기타 (처리)	BEE_PRO_ETC
CREATE TABLE BEE_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT BEE_PRO_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
    ,CONSTRAINT BEE_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES BEE_REP(REP_ID)
);


--○ 정모평가(댓글형)	BEE_EVAL	
CREATE TABLE BEE_EVAL (
	BEE_EVAL_ID	VARCHAR2(20)	
	,REQ_ID	    VARCHAR2(20)	NOT NULL --모임신청 코드
	,SCORE	    NUMBER	        NOT NULL -- 별점
	,CONTENT	VARCHAR2(2000)	        --내용(코멘트)
	,BDATE	    DATE	        DEFAULT SYSDATE
    ,CONSTRAINT BEE_EVAL_BEE_EVAL_ID_PK PRIMARY KEY(BEE_EVAL_ID)
    ,CONSTRAINT BEE_EVAL_REQ_ID_FK FOREIGN KEY(REQ_ID)
                REFERENCES BEE_REQ(REQ_ID)
);


-- 개인평가 15 
CREATE TABLE MEMBER_EVAL (

	MEM_EVAL_ID	VARCHAR2(20)	,
	BDATE	DATE	DEFAULT SYSDATE,
	EVAL_ID	VARCHAR2(20)	NOT NULL,
	WRITER_ID	VARCHAR2(20)	NOT NULL,   -- 평가자
	REQ_ID	VARCHAR2(20)	NOT NULL,       -- 대상자
    
    CONSTRAINT PK_MEMBER_EVAL_MEM_EVAL_ID PRIMARY KEY(MEM_EVAL_ID),
    CONSTRAINT FK_MEMBER_EVAL_EVAL_ID FOREIGN KEY(EVAL_ID) REFERENCES EVAL_ITEM(EVAL_ID),
    CONSTRAINT FK_MEMBER_EVAL_WRITER_ID FOREIGN KEY(WRITER_ID) REFERENCES BEE_REQ(REQ_ID),
    CONSTRAINT FK_MEMBER_EVAL_REQ_ID FOREIGN KEY(REQ_ID) REFERENCES BEE_REQ(REQ_ID)
);

--○ 모집	 RECRUIT_BOARD
CREATE TABLE RECRUIT_BOARD (
	B_ID	        VARCHAR2(20)	
	,CLUBMEM_ID	    VARCHAR2(20)	NOT NULL -- 모집 등록자
	,TITLE	        VARCHAR2(100)	NOT NULL
	,CONTENT	    VARCHAR2(4000)	
	,POSITION_ID	VARCHAR2(20)	NOT NULL -- 모집 직위
	,BDATE	        DATE	        DEFAULT SYSDATE --모집 등록일  
	,CNT	        NUMBER	        DEFAULT 0 
    ,CONSTRAINT RECRUIT_BOARD_B_ID_PK PRIMARY KEY(B_ID)
    ,CONSTRAINT RECRUIT_BOARD_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
    ,CONSTRAINT RECRUIT_BOARD_POSITION_ID_FK FOREIGN KEY(POSITION_ID)
                REFERENCES POSITION(POSITION_ID)
);


--○ 신청자	VOLUNTEER
CREATE TABLE VOLUNTEER (
	VOLUNTEER_ID	VARCHAR2(20)	
	,B_ID	        VARCHAR2(20)	NOT NULL --모집코드
	,CLUBMEM_ID	    VARCHAR2(20)	NOT NULL --동아리 회원코드
	,BDATE	        DATE	        DEFAULT SYSDATE --신청날짜
    ,CONSTRAINT VOLUNTEER_VOLUNTEER_ID_PK PRIMARY KEY(VOLUNTEER_ID)
    ,CONSTRAINT VOLUNTEER_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES RECRUIT_BOARD(B_ID)
    ,CONSTRAINT VOLUNTEER_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);


--○ 운영진 투표 발의	MOTION_VOTE
-- 모집이 종료된 후 선택자들 중에서의 투표 
CREATE TABLE MOTION_VOTE (
	MOTION_ID	VARCHAR2(20)   
	,B_ID	    VARCHAR2(20)	NOT NULL
	,BDATE	    DATE	        DEFAULT SYSDATE
    ,CONSTRAINT MOTION_VOTE_MOTION_ID_PK PRIMARY KEY(MOTION_ID)
    ,CONSTRAINT MOTION_VOTE_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES RECRUIT_BOARD(B_ID)
);


--○ 운영진 투표(신청자중 선택)	EXE_VOTE 
-- 운영진이 게시한 모집의 신청자들 중 선택한 신청자가 입력되는 테이블.
CREATE TABLE EXE_VOTE (
	EXE_VOTE_ID	    VARCHAR2(20)	
	,BDATE	        DATE	        DEFAULT SYSDATE --투표날짜
	,VOLUNTEER_ID	VARCHAR2(20)	NOT NULL --신청자ID
	,CLUBMEM_ID	    VARCHAR2(20)	NOT NULL --투표자(운영진)ID
	,MOTION_ID	    VARCHAR2(20)	NOT NULL --투표발의ID
    ,CONSTRAINT EXE_VOTE_EXE_VOTE_ID_PK PRIMARY KEY(EXE_VOTE_ID)
    ,CONSTRAINT EXE_VOTE_VOLUNTEER_ID_FK FOREIGN KEY(VOLUNTEER_ID)
                REFERENCES VOLUNTEER(VOLUNTEER_ID)
    ,CONSTRAINT EXE_VOTE_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
    ,CONSTRAINT EXE_VOTE_MOTION_ID_FK FOREIGN KEY(MOTION_ID)
                REFERENCES MOTION_VOTE(MOTION_ID)
);


--○ 투표 게시판
CREATE TABLE VOTE_BOARD 
( B_ID          VARCHAR2(20)   
, VOTE_ID       VARCHAR2(20)    NOT NULL
, WRITER        VARCHAR2(20)    NOT NULL    --발의자
, CLUBMEM_ID    VARCHAR2(20)    NOT NULL    --대상자
, CNT           NUMBER          DEFAULT 0
, BDATE          DATE            DEFAULT SYSDATE
, TITLE         VARCHAR2(100)   NOT NULL
, CONSTRAINT VOTE_BOARD_B_ID_PK PRIMARY KEY(B_ID)
, CONSTRAINT VOTE_BOARD_VOTE_ID_FK FOREIGN KEY(VOTE_ID) REFERENCES VOTE_TYPE(VOTE_ID)
, CONSTRAINT VOTE_BOARD_WRITER_FK FOREIGN KEY(WRITER) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT VOTE_BOARD_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);

--○ 투표자
CREATE TABLE VOTER 
( VOTER_ID      VARCHAR2(20)   
, B_ID          VARCHAR2(20)    NOT NULL
, CLUBMEM_ID    VARCHAR2(20)    NOT NULL
, BDATE          DATE            NULL
, PAC_ID        VARCHAR2(20)    NOT NULL
, CONSTRAINT VOTER_VOTER_ID_PK PRIMARY KEY(VOTER_ID)
, CONSTRAINT VOTER_B_ID_FK FOREIGN KEY(B_ID) REFERENCES VOTE_BOARD(B_ID)
, CONSTRAINT VOTER_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT VOTER_PAC_ID_FK FOREIGN KEY(PAC_ID) REFERENCES P_A_C(PAC_ID)
);

--○ 자주하는 질문	FAQ
CREATE TABLE FAQ (
	FAQ_ID	    VARCHAR2(20)	
	,ADMIN_ID	VARCHAR2(20)	NOT NULL --작성자(관리자ID)
	,BDATE	    DATE	        DEFAULT SYSDATE
	,TITLE	    VARCHAR2(100)	NOT NULL
	,CONTENT	VARCHAR2(4000)	NOT NULL
    ,CONSTRAINT FAQ_FAQ_ID_PK PRIMARY KEY(FAQ_ID)
    ,CONSTRAINT FAQ_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
);

-- 공지사항 10 
CREATE TABLE NOTICE (
	B_ID	VARCHAR2(20),
	ADMIN_ID	VARCHAR2(20)NOT NULL,
	TITLE	VARCHAR2(100)NOT NULL,
	CONTENT	VARCHAR2(4000)NOT NULL,
	BDATE	DATE	DEFAULT SYSDATE,
	CNT	    NUMBER DEFAULT 0,
    
    CONSTRAINT PK_NOTICE_B_ID PRIMARY KEY(B_ID),
    CONSTRAINT FK_NOTICE_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)  
);


--○ 메인 - 자유게시판	FREE_B
CREATE TABLE FREE_B (
	B_ID	    VARCHAR2(20)	
	,MID	    VARCHAR2(20)	NOT NULL
	,TITLE	    VARCHAR2(100)	NOT NULL
	,CONTENT    VARCHAR2(4000)	NOT NULL
	,BDATE	    DATE	        DEFAULT SYSDATE
	,CNT	    NUMBER	        DEFAULT 0
    ,CONSTRAINT FREE_B_B_ID_PK PRIMARY KEY(B_ID)
    ,CONSTRAINT FREE_B_MID_FK FOREIGN KEY(MID)
                REFERENCES MEMBER(MID)
);

--○ 자유게시판 좋아요	FREE_B_LIKE	
CREATE TABLE FREE_B_LIKE (
	LIKE_ID	    VARCHAR2(20)
	,BDATE	    DATE	            DEFAULT SYSDATE
	,B_ID	    VARCHAR2(20)	    NOT NULL
	,MID	        VARCHAR2(20)	NOT NULL
    ,CONSTRAINT FREE_B_LIKE_LIKE_ID_PK PRIMARY KEY(LIKE_ID)
    ,CONSTRAINT FREE_B_LIKE_MID_FK FOREIGN KEY(MID)
                REFERENCES MEMBER(MID)
);

--○ 자유게시판 관리자 삭제	FREE_B_DEL
CREATE TABLE FREE_B_DEL (
	BD_ID	    VARCHAR2(20)	
	,BDATE	    DATE	        DEFAULT SYSDATE
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
	,B_ID	    VARCHAR2(20)	NOT NULL
	,REASON_ID	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT FREE_B_DEL_BD_ID_PK PRIMARY KEY(BD_ID)
    ,CONSTRAINT FREE_B_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT FREE_B_DEL_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES FREE_B(B_ID)
    ,CONSTRAINT FREE_B_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
);
--==>> Table FREE_B_DEL이(가) 생성되었습니다.


--○ 컨텐츠 신고 접수(자유게시판)
CREATE TABLE FREE_B_REP 
( REP_ID        VARCHAR2(20)    
, B_ID          VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, R_REASON_ID   VARCHAR2(20)    NOT NULL
, MID           VARCHAR2(20)    NOT NULL
, PRO_DATE      DATE            NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, ADMIN_ID      VARCHAR2(20)    NULL
, CONSTRAINT FREE_B_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT FREE_B_REP_BC_ID_FK FOREIGN KEY(B_ID) REFERENCES FREE_B(B_ID)
, CONSTRAINT FREE_B_REP_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
, CONSTRAINT FREE_B_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT FREE_B_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT FREE_B_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
);


--○ 기타 선택 시(신고)  
CREATE TABLE FREE_B_REP_ETC (
	R_ETC_ID	VARCHAR2(20),
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_FREE_B_REP_ETC_R_ETC_ID PRIMARY KEY(R_ETC_ID),
    CONSTRAINT FK_FREE_B_REP_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES FREE_B_REP(REP_ID)  
);

 
--○기타 선택 시(처리) 
CREATE TABLE FREE_B_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_FREE_B_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT FK_FREE_B_PRO_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES FREE_B_REP(REP_ID)
);

 
--○ 홍보 게시판
CREATE TABLE PROMOTION_B 
( B_ID          VARCHAR2(20)    
, CLUBMEM_ID    VARCHAR2(20)    NOT NULL
, BDATE          DATE            DEFAULT SYSDATE
, TITLE         VARCHAR2(20)    NOT NULL
, CONTENT       VARCHAR2(4000)  NOT NULL
, CNT           NUMBER          DEFAULT 0
, CONSTRAINT PROMOTION_B_B_ID_PK PRIMARY KEY(B_ID)
, CONSTRAINT PROMOTION_B_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);


--○ 홍보 게시판 좋아요
CREATE TABLE PROMOTION_B_LIKE 
( LIKE_ID       VARCHAR2(20)   
, B_ID          VARCHAR2(20)    NOT NULL
, BDATE          DATE            DEFAULT SYSDATE
, MID           VARCHAR2(20)    NOT NULL
, CONSTRAINT PROMOTION_B_LIKE_LIKE_ID_PK PRIMARY KEY(LIKE_ID)
, CONSTRAINT PROMOTION_B_LIKE_B_ID_FK FOREIGN KEY(B_ID) REFERENCES PROMOTION_B(B_ID)
, CONSTRAINT PROMOTION_B_LIKE_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);
--==>> Table PROMOTION_B_LIKE이(가) 생성되었습니다.


--○ 홍보게시판 관리자 삭제
CREATE TABLE PROMOTION_DEL 
( BD_ID         VARCHAR2(20)    
, BDATE          DATE            DEFAULT SYSDATE
, ADMIN_ID      VARCHAR2(20)    NOT NULL
, REASON_ID     VARCHAR2(20)    NOT NULL
, B_ID          VARCHAR2(20)    NOT NULL
, CONSTRAINT PROMOTION_DEL_BD_ID_PK PRIMARY KEY(BD_ID)
, CONSTRAINT PROMOTION_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT PROMOTION_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID)
, CONSTRAINT PROMOTION_DEL_B_ID_FK FOREIGN KEY(B_ID) REFERENCES PROMOTION_B(B_ID)
);

--○ 컨텐츠 신고접수(홍보게시판) 
CREATE TABLE PROMOTION_B_REP 
( REP_ID        VARCHAR2(20)   
, B_ID          VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, MID           VARCHAR2(20)    NOT NULL
, R_REASON_ID   VARCHAR2(20)    NULL
, PRO_DATE      DATE            NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, ADMIN_ID      VARCHAR2(20)    NULL
, CONSTRAINT PROMOTION_B_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT PROMOTION_B_REP_BC_ID_FK FOREIGN KEY(B_ID) REFERENCES PROMOTION_B(B_ID)
, CONSTRAINT PROMOTION_B_REP_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
, CONSTRAINT PROMOTION_B_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT PROMOTION_B_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT PROMOTION_B_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
);

--○ 홍보 기타 (신고)
CREATE TABLE PROMOTION_B_REP_ETC 
( R_ETC_ID      VARCHAR2(20)   
, CONTENT       VARCHAR2(500)   NOT NULL
, REP_ID        VARCHAR2(20)    NOT NULL
, CONSTRAINT P_B_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
, CONSTRAINT P_B_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES PROMOTION_B_REP(REP_ID)
);

--○ 홍보 기타(처리)
CREATE TABLE PROMOTION_B_PRO_ETC 
( P_ETC_ID      VARCHAR2(20)    
, CONTENT       VARCHAR2(500)   NOT NULL
, REP_ID        VARCHAR2(20)    NOT NULL
, CONSTRAINT P_B_PRO_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
, CONSTRAINT P_B_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES PROMOTION_B_REP(REP_ID)
);

--○ 카테고리별 게시판
CREATE TABLE CATEGORY_B 
( B_ID	            VARCHAR2(20)	
, CATEGORY_S_ID	    VARCHAR2(20)	    NOT NULL
, TITLE	            VARCHAR2(100)	NOT NULL
, CONTENT	        VARCHAR2(4000)	NOT NULL
, CNT	            NUMBER	        DEFAULT 0
, BDATE	            DATE	        DEFAULT SYSDATE
, MID	            VARCHAR2(20)	    NOT NULL
, CONSTRAINT CATEGORY_B_B_ID_PK PRIMARY KEY(B_ID)
, CONSTRAINT CATEGORY_B_CATEGORY_S_ID_FK FOREIGN KEY(CATEGORY_S_ID) REFERENCES CATEGORY_S(CATEGORY_S_ID)
, CONSTRAINT CATEGORY_B_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);

--○ 카테고리별 게시판 좋아요
CREATE TABLE CATEGORY_B_LIKE 
( LIKE_ID       VARCHAR2(20)   NOT NULL
, BDATE          DATE           DEFAULT SYSDATE
, B_ID          VARCHAR2(20)   NOT NULL
, MID           VARCHAR2(20)   NOT NULL
, CONSTRAINT CATEGORY_B_LIKE_LIKE_ID_PK PRIMARY KEY(LIKE_ID)
, CONSTRAINT CATEGORY_B_LIKE_B_ID_FK FOREIGN KEY(B_ID) REFERENCES CATEGORY_B(B_ID)
, CONSTRAINT CATEGORY_B_LIKE_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);

 
--○ 카테고리별 게시판 관리자 삭제
CREATE TABLE CATEGORY_B_DEL 
( BDC_ID        VARCHAR2(20)   
, BDATE         DATE           DEFAULT SYSDATE
, ADMIN_ID      VARCHAR2(20)   NOT NULL
, REASON_ID     VARCHAR2(20)   NOT NULL
, B_ID          VARCHAR2(20)   NOT NULL
, CONSTRAINT CATEGORY_B_DEL_BDC_ID_PK PRIMARY KEY(BDC_ID)
, CONSTRAINT CATEGORY_B_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT CATEGORY_B_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID)
, CONSTRAINT CATEGORY_B_DEL_B_ID_FK FOREIGN KEY(B_ID) REFERENCES CATEGORY_B(B_ID)
);


--○ 컨텐츠신고접수(카테고리별게시판)
CREATE TABLE CATEGORY_B_REP 
( REP_ID        VARCHAR2(20)    NOT NULL
, B_ID          VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, MID           VARCHAR2(20)    NOT NULL
, R_REASON_ID   VARCHAR2(20)    NOT NULL
, PRO_DATE      DATE            NULL
, ADMIN_ID      VARCHAR2(20)    NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, CONSTRAINT CATEGORY_B_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT CATEGORY_B_REP_BC_ID_FK FOREIGN KEY(B_ID) REFERENCES CATEGORY_B(B_ID)
, CONSTRAINT CATEGORY_B_REP_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
, CONSTRAINT CATEGORY_B_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT CATEGORY_B_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT CATEGORY_B_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
);


--○ 카테고리별게시판 기타 선택 시(신고)
CREATE TABLE CATEGORY_B_REP_ETC 
( R_ETC_ID      VARCHAR2(20)   
, CONTENT       VARCHAR2(500)   NOT NULL
, REP_ID        VARCHAR2(20)   NOT NULL
, CONSTRAINT CAT_B_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
, CONSTRAINT CAT_B_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES CATEGORY_B_REP(REP_ID)
);


--○ 카테고리별게시판 기타 선택 시(처리)
CREATE TABLE CATEGORY_B_PRO_ETC 
( P_ETC_ID   VARCHAR2(20)   
, CONTENT   VARCHAR2(500)   NOT NULL
, REP_ID   VARCHAR2(20)   NOT NULL
, CONSTRAINT CAT_B_PRO_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
, CONSTRAINT CAT_B_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES CATEGORY_B_REP(REP_ID)
);


--○ 자유게시판별 댓글	FREE_B_C
CREATE TABLE FREE_B_C (
	BC_ID	    VARCHAR2(20)	
	,B_ID	    VARCHAR2(20)	NOT NULL
	,MID	    VARCHAR2(20)	NOT NULL
	,CONTENT	VARCHAR2(1000)	NOT NULL
	,BDATE	    DATE	        DEFAULT SYSDATE
    ,CONSTRAINT FREE_B_C_BC_ID_PK PRIMARY KEY(BC_ID)
    ,CONSTRAINT FREE_B_C_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES FREE_B(B_ID)
    ,CONSTRAINT FREE_B_C_MID_FK FOREIGN KEY(MID)
                REFERENCES MEMBER(MID)
);


--○ 자유게시판 댓글별 좋아요	FREE_B_C_LIKE
CREATE TABLE FREE_B_C_LIKE (
	LIKE_ID	    VARCHAR2(20)	
	,BDATE	    DATE	        DEFAULT SYSDATE
	,BC_ID	    VARCHAR2(20)	NOT NULL
	,MID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT FREE_B_C_LIKE_LIKE_ID_PK PRIMARY KEY(LIKE_ID)
    ,CONSTRAINT FREE_B_C_LIKE_BC_ID_FK FOREIGN KEY(BC_ID)
                REFERENCES FREE_B_C(BC_ID)
    ,CONSTRAINT FREE_B_C_LIKE_MID_FK FOREIGN KEY(MID)
                REFERENCES MEMBER(MID)
);


--○ 자유게시판 댓글관리자 삭제	FREE_B_C_DEL
CREATE TABLE FREE_B_C_DEL (
	BCD_ID	    VARCHAR2(20)	
	,BDATE	    DATE	        DEFAULT SYSDATE
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
	,BC_ID	    VARCHAR2(20)	NOT NULL
	,REASON_ID	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT FREE_B_C_DEL_BCD_ID_PK PRIMARY KEY(BCD_ID)
    ,CONSTRAINT FREE_B_C_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT FREE_B_C_DEL_BC_ID_FK FOREIGN KEY(BC_ID)
                REFERENCES FREE_B_C(BC_ID)
    ,CONSTRAINT FREE_B_C_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
);


--○ 컨텐츠 신고 접수(자유게시판 댓글)
CREATE TABLE FREE_B_C_REP 
( REP_ID        VARCHAR2(20)    
, BC_ID         VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, R_REASON_ID   VARCHAR2(20)    NOT NULL
, MID           VARCHAR2(20)    NOT NULL
, PRO_DATE      DATE            NULL
, ADMIN_ID      VARCHAR2(20)    NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, CONSTRAINT FREE_B_C_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT FREE_B_C_REP_BC_ID_FK FOREIGN KEY(BC_ID) REFERENCES FREE_B_C(BC_ID)
, CONSTRAINT FREE_B_C_REP_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
, CONSTRAINT FREE_B_C_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT FREE_B_C_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT FREE_B_C_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);  


--○기타 선택 시(접수)     
CREATE TABLE FREE_B_C_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_FREE_B_C_REP_ETC_R_ETC_ID PRIMARY KEY(R_ETC_ID),
    CONSTRAINT FK_FREE_B_C_REP_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES FREE_B_C_REP(REP_ID)  
);


--○기타 선택 시(처리) 
CREATE TABLE FREE_B_C_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	NOT NULL,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_FREE_B_C_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT FK_FREE_B_C_PRO_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES FREE_B_C_REP(REP_ID)
);


--○ 홍보 게시판 코드별 댓글
CREATE TABLE PROMOTION_B_C 
( BC_ID     VARCHAR2(20)    
, B_ID      VARCHAR2(20)    NOT NULL
, MID       VARCHAR2(20)    NOT NULL
, CONTENT   VARCHAR2(1000)  NOT NULL
, DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT PROMOTION_B_C_BC_ID_PK PRIMARY KEY(BC_ID)
, CONSTRAINT PROMOTION_B_C_B_ID_FK FOREIGN KEY(B_ID) REFERENCES PROMOTION_B(B_ID)
, CONSTRAINT PROMOTION_B_C_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);


--○ 홍보게시판 댓글 좋아요
CREATE TABLE PROMOTION_C_LIKE 
( LIKE_ID   VARCHAR2(20)   
, BC_ID    VARCHAR2(20)    NOT NULL
, DATE      DATE            DEFAULT SYSDATE
, MID       VARCHAR2(20)    NOT NULL
, CONSTRAINT PROMOTION_C_LIKE_LIKE_ID_PK PRIMARY KEY(LIKE_ID)
, CONSTRAINT PROMOTION_C_LIKE_BC_ID_FK FOREIGN KEY(BC_ID) REFERENCES PROMOTION_B_C(BC_ID)
, CONSTRAINT PROMOTION_C_LIKE_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);


--○ 홍보게시판 댓글 관리자 삭제
CREATE TABLE PROMOTION_C_DEL 
( BCD_ID        VARCHAR2(20)   
, DATE          DATE            NOT NULL
, ADMIN_ID      VARCHAR2(20)    NOT NULL
, REASON_ID     VARCHAR2(20)    NOT NULL
, BC_ID         VARCHAR2(20)    NOT NULL
, CONSTRAINT PROMOTION_C_DEL_BCD_ID_PK PRIMARY KEY(BCD_ID)
, CONSTRAINT PROMOTION_C_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT PROMOTION_C_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID)
, CONSTRAINT PROMOTION_C_DEL_BC_ID_FK FOREIGN KEY(BC_ID) REFERENCES PROMOTION_B_C(BC_ID)
);


--○ 컨텐츠 신고접수(홍보게시판댓글)
CREATE TABLE PROMOTION_B_C_REP 
( REP_ID        VARCHAR2(20)   
, BC_ID         VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, R_REASON_ID   VARCHAR2(20)    NOT NULL
, MID           VARCHAR2(20)    NOT NULL
, PRO_DATE      DATE            NULL
, ADMIN_ID      VARCHAR2(20)    NOT NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, CONSTRAINT P_B_C_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT P_B_C_REP_BC_ID_FK FOREIGN KEY(BC_ID) REFERENCES PROMOTION_B_C(BC_ID)
, CONSTRAINT P_B_C_REP_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
, CONSTRAINT P_B_C_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(R_REASON_ID)
, CONSTRAINT P_B_C_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(P_REASON_ID)
, CONSTRAINT P_B_C_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);


--○ 기타 선택(신고) 
CREATE TABLE PROMOTION_B_C_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    CONSTRAINT PK_PROMOTION_B_C_REP_ETC_R_ETC_ID PRIMARY KEY(R_ETC_ID),
    CONSTRAINT FK_PROMOTION_B_C_REP_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES PROMOTION_B_C_REP(REP_ID)
);

 
--○  기타 선택 시(처리) 
CREATE TABLE PROMOTION_B_C_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_PROMOTION_B_C_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT FK_PROMOTION_B_C_PRO_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES PROMOTION_B_C_REP(REP_ID)
);

 
--○ 대표게시판 카테고리별 댓글 
CREATE TABLE CATEGORY_B_C (
	BC_ID	VARCHAR2(20),
	B_ID	VARCHAR2(20) NOT NULL,
	TITLE	VARCHAR2(1000) NOT NULL,
	DATE	DATE	DEFAULT SYSDATE,
	MID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CATEGORY_B_C_BC_ID PRIMARY KEY(BC_ID),
    CONSTRAINT FK_CATEGORY_B_C_B_ID FOREIGN KEY(B_ID) REFERENCES CATEGORY_B(B_ID),
    CONSTRAINT FK_CATEGORY_B_C_MID FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);


--○ 대표게시판 카테고리별 댓글 좋아요
CREATE TABLE CATEGORY_B_C_LIKE (

	LIKE_ID	VARCHAR2(20),
	DATE	DATE	DEFAULT SYSDATE,
	BC_ID	VARCHAR2(20)	NOT NULL,
	MID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CATEGORY_B_C_LIKE_LIKE_ID PRIMARY KEY(LIKE_ID),
    CONSTRAINT FK_CATEGORY_B_C_LIKE_BC_ID FOREIGN KEY(BC_ID) REFERENCES CATEGORY_B_C(BC_ID),
    CONSTRAINT FK_CATEGORY_B_C_LIKE_MID FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);

--○ 대표게시판 카테고리별 댓글 관리자 삭제
CREATE TABLE CATEGORY_B_C_DEL (
	BD_ID	VARCHAR2(20)	,
	DATE	DATE	DEFAULT SYSDATE,
	ADMIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(20)	NOT NULL,
	BC_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CATEGORY_B_C_DEL_BD_ID PRIMARY KEY(BD_ID),
    CONSTRAINT FK_CATEGORY_B_C_DEL_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_CATEGORY_B_C_DEL_REASON_ID FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID),
    CONSTRAINT FK_CATEGORY_B_C_DEL_BC_ID FOREIGN KEY(BC_ID) REFERENCES CATEGORY_B_C(BC_ID)
    
);


--○ 컨텐츠신고접수(카테고리별게시판댓글)
CREATE TABLE CATEGORY_B_C_REP 
( REP_ID        VARCHAR2(20)    
, BC_ID         VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, MID           VARCHAR2(20)    NOT NULL
, R_REASON_ID   VARCHAR2(20)    NOT NULL
, PRO_DATE      DATE            NULL
, ADMIN_ID      VARCHAR2(20)    NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, CONSTRAINT C_B_C_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT C_B_C_REP_BC_ID_FK FOREIGN KEY(BC_ID) REFERENCES CATEGORY_B_C(BC_ID)
, CONSTRAINT C_B_C_REP_MID_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID)
, CONSTRAINT C_B_C_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(R_REASON_ID)
, CONSTRAINT C_B_C_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(P_REASON_ID)
, CONSTRAINT C_B_C_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);


--○ 카테고리게시판 댓글 기타(신고)
CREATE TABLE CATEGORY_B_C_REP_ETC 
( R_ETC_ID      VARCHAR2(20)   
, CONTENT       VARCHAR2(500)   NOT NULL
, REP_ID        DATE            NOT NULL
, CONSTRAINT CAT_B_C_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
, CONSTRAINT CATEGORY_B_C_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES CATEGORY_B_C_REP(REP_ID)
);

-- 카테고리게시판 댓글 기타(처리)                                                
CREATE TABLE CATEGORY_B_C_PRO_ETC (
   P_ETC_ID   VARCHAR2(20)   NOT NULL,
   CONTENT    VARCHAR2(500)   NOT NULL,
   REP_ID   DATE   NOT NULL
   , CONSTRAINT CAT_B_C_PRO_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
, CONSTRAINT CATEGORY_B_C_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES CATEGORY_B_C_REP(REP_ID)
);


--메인                                                                          --메인(비회원문의, 1:1문의)

--○ 비회원 문의	NON_INQUIRY
CREATE TABLE NON_INQUIRY (
	B_ID	    VARCHAR2(20)	
	,PWD	    VARCHAR2(16)	NOT NULL -- 비회원 문의 비밀번호
	,DATE	    DATE	        DEFAULT SYSDATE --등록일
	,TITLE	    VARCHAR2(100)	NOT NULL --문의 제목
	,CONTENT	VARCHAR2(4000)	NOT NULL --문의 내용
	,NAME	    VARCHAR2(40)	NOT NULL --비회원 작성자
	,EMAIL	    VARCHAR2(100)	NOT NULL --비회원 작성자 이메일
    ,CONSTRAINT NON_INQUIRY_B_ID_PK PRIMARY KEY(B_ID)
);


--○ 비회원 문의 관리자 삭제	NON_INQUIRY_DEL
CREATE TABLE NON_INQUIRY_DEL (
	BD_ID	    VARCHAR2(20)	
	,DATE	    DATE	        DEFAULT SYSDATE
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
	,B_ID	    VARCHAR2(20)	NOT NULL
	,REASON_ID	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT NON_INQUIRY_DEL_BD_ID_PK PRIMARY KEY(BD_ID)
    ,CONSTRAINT NON_INQUIRY_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT NON_INQUIRY_DEL_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES NON_INQUIRY(B_ID)
    ,CONSTRAINT NON_INQUIRY_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
);


--○ 비회원문의 답변(댓글)	ANS_NON_INQUIRY
CREATE TABLE ANS_NON_INQUIRY (
	BC_ID	    VARCHAR2(20)	
	,B_ID	    VARCHAR2(20)	NOT NULL
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
	,CONTENT	VARCHAR2(4000)	NOT NULL
	,DATE	    DATE	        DEFAULT SYSDATE
    ,CONSTRAINT ANS_NON_INQUIRY_BC_ID_PK PRIMARY KEY(BC_ID)
    ,CONSTRAINT ANS_NON_INQUIRY_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES NON_INQUIRY(B_ID)
    ,CONSTRAINT ANS_NON_INQUIRY_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
);

--○ 1:1 문의  
CREATE TABLE MEM_INQUIRY (
	B_ID	VARCHAR2(20)	,
	DATE	DATE	DEFAULT SYSDATE,
	MID	VARCHAR2(20)	NOT NULL,
	TITLE	VARCHAR2(100)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
    
    CONSTRAINT PK_MEM_INQUIRY_B_ID PRIMARY KEY(B_ID),
    CONSTRAINT FK_MEM_INQUIRY_MID FOREIGN KEY MEMBER(MID)
);


--○ 1:1 문의 사진  
CREATE TABLE MEM_INQUIRY_PHOTO (
	PHOTO_ID	VARCHAR2(20),
	B_ID	VARCHAR2(20) NOT NULL,
	URL	VARCHAR2(500),
    
    CONSTRAINT PK_MEM_INQUIRY_PHOTO_PHOTO_ID PRIMARY KEY(PHOTO_ID),
    CONSTRAINT FK_MEM_INQUIRY_PHOTO_B_ID FOREIGN KEY(B_ID) REFERENCES MEM_INQUIRY(B_ID)
);

--○ 1:1문의 관리 
CREATE TABLE ANS_MEM_INQUIRY (
	BC_ID VARCHAR2(20)	,
	B_ID	VARCHAR2(20) NOT NULL,
	ADMIN_ID	VARCHAR2(20),
	CONTENT	VARCHAR2(4000),
	DATE	DATE	DEFAULT SYSDATE,
    
    CONSTRAINT PK_ANS_MEM_INQUIRY_BC_ID PRIMARY KEY(BC_ID),
    CONSTRAINT FK_ANS_MEM_INQUIRY_B_ID FOREIGN KEY(B_ID) REFERENCES MEM_INQUIRY(B_ID),
    CONSTRAINT FK_ANS_MEM_INQUIRY_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

 
--○ 1:1문의 관리자 삭제 
CREATE TABLE MEM_INQUIRY_DEL (
	BD_ID	VARCHAR2(20)	,
	B_ID	VARCHAR2(20)	NOT NULL,
	CONTENT	VARCHAR(500)	NOT NULL,
	ADMIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_MEM_INQUIRY_DEL_BD_ID PRIMARY KEY(BD_ID),
    CONSTRAINT FK_MEM_INQUIRY_DEL_B_ID FOREIGN KEY(B_ID) REFERENCES MEM_INQUIRY(B_ID),
    CONSTRAINT FK_MEM_INQUIRY_DEL_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_MEM_INQUIRY_DEL_REASON_ID FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID)
);

 

--[동아리 게시판]                                                               --[동아리 게시판]
--공지사항, 자유글, 가입인사, 사진첩, 정모후기, 문의글

--○ 동아리게시판공지사항	CLUB_NOTICE
CREATE TABLE CLUB_NOTICE (
	B_ID	    VARCHAR2(20)	
	,CLUBMEM_ID	VARCHAR2(20)	    NOT NULL
	,TITLE	    VARCHAR2(100)	    NOT NULL
	,CONTENT	VARCHAR2(4000)	    NOT NULL
	,BDATE	    DATE	            DEFAULT SYSDATE
	,CNT	        NUMBER	        DEFAULT 0 
    ,CONSTRAINT CLUB_NOTICE_B_ID_PK PRIMARY KEY(B_ID)
    ,CONSTRAINT CLUB_NOTICE_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);

--○ 동아리게시판공지사항관리자삭제	CLUB_NOTICE_DEL
CREATE TABLE CLUB_NOTICE_DEL (
	BD_ID	    VARCHAR2(20)	
	,BDATE	    DATE	        DEFAULT SYSDATE
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
    ,REASON_ID	VARCHAR2(20)	NOT NULL
	,B_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_NOTICE_DEL_BD_ID_PK PRIMARY KEY(BD_ID)
    ,CONSTRAINT CLUB_NOTICE_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT CLUB_NOTICE_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
    ,CONSTRAINT CLUB_NOTICE_DEL_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES CLUB_NOTICE(B_ID)
);
                                                                                --------------신고접수 추가하기
--○ 동아리게시판 컨텐츠 신고 접수
CREATE TABLE CLUB_NOTICE_REP 
( REP_ID	    VARCHAR2(20)	    
, B_ID	        VARCHAR2(20)    	NOT NULL
, CLUBMEM_ID	VARCHAR2(20)	    NOT NULL    -- 신고자
, REP_DATE	    DATE	        DEFAULT SYSDATE
, R_REASON_ID	    VARCHAR2(20)	    NOT NULL
, ADMIN_ID	    VARCHAR2(20)    	NULL
, P_REASON_ID	    VARCHAR2(20)    	NULL
, PRO_DATE	    DATE	        NULL
, CONSTRAINT CLUB_N_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT CLUB_N_REP_ID_FK FOREIGN KEY(B_ID) REFERENCES CLUB_NOTICE(B_ID)
, CONSTRAINT CLUB_N_REP_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT CLUB_N_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT CLUB_N_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT CLUB_N_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
);

--○ 동아리 공지 신고접수 기타
CREATE TABLE CLUB_NOTICE_REP_ETC
( R_ETC_ID	VARCHAR2(20)	    
, CONTENT	VARCHAR2(500)	NOT NULL
, REP_ID	VARCHAR2(20)	    NOT NULL
, CONSTRAINT CLUB_N_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
, CONSTRAINT CLUB_N_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES CLUB_NOTICE_REP(REP_ID)
);


--○ 동아리 공지 처리 기타 
CREATE TABLE CLUB_NOTICE_PRO_ETC 
( P_ETC_ID	VARCHAR2(20)    
, CONTENT	VARCHAR2(500)	NOT NULL
, REP_ID	VARCHAR2(20)    	NOT NULL
, CONSTRAINT C_N_PRO_ETC_P_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
, CONSTRAINT C_N_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID) REFERENCES CLUB_NOTICE_REP(REP_ID)
);
                                              
                                                                             


--○ 동아리게시판 자유글
CREATE TABLE CLUB_FREE_B
(
	B_ID	        VARCHAR2(20)	
	, CLUBMEM_ID	VARCHAR2(20)    	NOT NULL
	, TITLE	        VARCHAR2(100)	NOT NULL
	, CONTENT	    VARCHAR2(4000)	NOT NULL
	, BDATE	        DATE	        DEFAULT SYSDATE
	, CNT	        NUMBER	        DEFAULT 0
    ,CONSTRAINT CLUB_FREE_B_B_ID_PK PRIMARY KEY(B_ID)
    ,CONSTRAINT CLUB_FREE_B_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);


--○ 동아리게시판 자유글 사진	CLUB_FREE_B_PHOTO
CREATE TABLE CLUB_FREE_B_PHOTO (
	PHOTO_ID	VARCHAR2(20)	
	,B_ID	VARCHAR2(20)	NOT NULL --게시글 ID
	,URL	VARCHAR2(500)	NOT NULL -- 사진 경로
    ,CONSTRAINT CLUB_FREE_B_PHOTO_PHOTO_ID_PK PRIMARY KEY(PHOTO_ID)
    ,CONSTRAINT CLUB_FREE_B_C_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES CLUB_FREE_B(B_ID)
);


--○ 동아리게시판 자유글 좋아요	CLUB_FREE_B_LIKE	
CREATE TABLE CLUB_FREE_B_LIKE (
	LIKE_ID	        VARCHAR2(20)	
	,BDATE	        DATE	        DEFAULT SYSDATE
	,B_ID	        VARCHAR2(20)	NOT NULL --게시글 코드
	,CLUBMEM_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_FREE_B_LIKE_LIKE_ID_PK PRIMARY KEY(LIKE_ID)
    ,CONSTRAINT CLUB_FREE_B_LIKE_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES CLUB_FREE_B(B_ID)
    ,CONSTRAINT CLUB_FREE_B_LIKE_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)           
);

--○ 동아리게시판 자유글 관리자 삭제	CLUB_FREE_B_DEL	
CREATE TABLE CLUB_FREE_B_DEL (
	BD_ID	    VARCHAR2(20)	
	,BDATE	    DATE	        DEFAULT SYSDATE  --삭제일
	,ADMIN_ID	VARCHAR2(20)	NOT NULL --관리자 id
	,REASON_ID	VARCHAR2(20)	NOT NULL -- 삭제 사유 
	,B_ID	    VARCHAR2(20)	NOT NULL --게시글 id
    ,CONSTRAINT CLUB_FREE_B_DEL_BD_ID_PK PRIMARY KEY (BD_ID)
    ,CONSTRAINT CLUB_FREE_B_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT CLUB_FREE_B_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
    ,CONSTRAINT CLUB_FREE_B_DEL_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES CLUB_FREE_B(B_ID)
            
);


--○ 컨텐츠신고접수(동아리-자유글)
CREATE TABLE CLUB_FREE_B_REP 
( REP_ID	    VARCHAR2(20)    
, B_ID	        VARCHAR2(20)    	NOT NULL
, CLUBMEM_ID	VARCHAR2(20)    	NOT NULL
, REP_DATE	    DATE	        DEFAULT SYSDATE
, R_REASON_ID	VARCHAR2(20)	    NOT NULL
, PRO_DATE	    DATE	        NULL
, ADMIN_ID	    VARCHAR2(20)    	NULL
, P_REASON_ID	VARCHAR2(20)    	NULL
, CONSTRAINT C_F_B_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT C_F_B_REP_BC_ID_FK FOREIGN KEY(B_ID) REFERENCES CLUB_FREE_B(B_ID)
, CONSTRAINT C_F_B_REP_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT C_F_B_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
, CONSTRAINT C_F_B_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT C_F_B_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(REASON_ID)
);


--○ 동아리자유글기타 선택 시(신고)	CLUB_FREE_B_REP_ETC
CREATE TABLE CLUB_FREE_B_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	
	,CONTENT 	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT C_F_B_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
    ,CONSTRAINT C_F_B_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_FREE_B_REP(REP_ID)
);


--○ 동아리자유글기타 선택 시(처리)	CLUB_FREE_B_PRO_ETC	
CREATE TABLE CLUB_FREE_B_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_FREE_B_PRO_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
    ,CONSTRAINT CLUB_FREE_B_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_FREE_B_REP(REP_ID)
);


--가입인사

--○ 동아리게시판 가입인사 
CREATE TABLE CLUB_INTRO (
	B_ID	VARCHAR2(20),	
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
	TITLE	VARCHAR2(100) NOT NULL,	
	CONTENT	VARCHAR2(4000)	NOT NULL,
	DATE	DATE	NULL,

    CONSTRAINT CLUB_INTRO_B_ID PRIMARY KEY(B_ID),
    CONSTRAINT CLUB_INTRO_CLUBMEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);


--○ 동아리게시판 가입인사 좋아요 
CREATE TABLE CLUB_INTRO_LIKE (
	LIKE_ID	VARCHAR2(20),
	DATE	DATE	DEFAULT SYSDATE,
    B_ID	VARCHAR2(20)	NOT NULL,
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_LIKE_LIKE_ID PRIMARY KEY(LIKE_ID),
    CONSTRAINT FK_CLUB_INTRO_LIKE_B_ID FOREIGN KEY(B_ID) REFERENCES CLUBMEMBERLIST(B_ID)
    
);


--○ 동아리 가입인사 관리자 삭제  
CREATE TABLE CLUB_INTRO_DEL (
	BD_ID	VARCHAR2(20)	,
	DATE	DATE	DEFAULT SYSDATE,
	ADMIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(20)	NOT NULL,
	B_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_DEL_BD_ID PRIMARY KEY(BD_ID),
    CONSTRAINT FK_CLUB_INTRO_DEL_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_CLUB_INTRO_DEL_REASON_ID FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID),
    CONSTRAINT FK_CLUB_INTRO_DEL_B_ID FOREIGN KEY(B_ID) REFERENCES CLUB_INTRO(B_ID)
);


--○ 가입인사 - 게시글 신고 접수 
CREATE TABLE CLUB_INTRO_REP (
	REP_ID	VARCHAR2(20)	,
	CLUBMEM_ID VARCHAR2(20)	NOT NULL,
	B_ID	VARCHAR2(20)	NOT NULL,
	REP_DATE DATE	DEFAULT SYSDATE,
	R_ETC_ID	VARCHAR2(20)	,
	ADMIN_ID	VARCHAR2(20)	,
	P_ETC_ID	VARCHAR2(20)	,
	PRO_DATE	DATE ,
    
    CONSTRAINT PK_CLUB_INTRO_REP_REP_ID PRIMARY KEY(REP_ID),
    CONSTRAINT FK_CLUB_INTRO_REP_CLUBMEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID),
    CONSTRAINT FK_CLUB_INTRO_REP_B_ID FOREIGN KEY(B_ID) REFERENCES CLUB_INTRO(B_ID),
    CONSTRAINT FK_CLUB_INTRO_REP_R_ETC_ID FOREIGN KEY(R_ETC_ID) HANDLE_REASON(R_ETC_ID),
    CONSTRAINT FK_CLUB_INTRO_REP_ADMIN_ID FOREIGN KEY(ADMIN_ID) ADMIN(ADMIN_ID),
    CONSTRAINT FK_CLUB_INTRO_REP_P_ETC_ID FOREIGN KEY(P_ETC_ID) HANDLE_REASON(P_ETC_ID)
);


--○ 가입인사 게시글 기타(신고)  
CREATE TABLE CLUB_INTRO_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_REP_ETC_R_ETC_ID PRIMARY KEY(R_ETC_ID),
    CONSTRAINT FK_CLUB_INTRO_REP_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES CLUB_INTRO_REP(REP_ID)    
);


--○ 가입인사 게시글 기타(처리) 
CREATE TABLE CLUB_INTRO_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT FK_CLUB_INTRO_PRO_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES CLUB_INTRO_REP(REP_ID)
);


--사진첩

--○ 동아리 사진첩	CLUB_GALLERY	
CREATE TABLE CLUB_GALLERY (
	GALLERY_ID	VARCHAR2(20)	
	,CLUBMEM_ID	VARCHAR2(20)	NOT NULL
	,DATE	    DATE	        DEFAULT SYSDATE
    ,CONSTRAINT CLUB_GALLERY_GALLERY_ID_PK PRIMARY KEY(GALLERY_ID)
);


--○ 사진첩 사진	CLUB_PHOTO
CREATE TABLE CLUB_PHOTO (
	PHOTO_ID	VARCHAR2(20)	
	,GALLERY_ID	VARCHAR2(20)	NOT NULL
	,URL     	VARCHAR2(500)	NOT NULL
    ,CONSTRAINT CLUB_PHOTO_PHOTO_ID_PK PRIMARY KEY(PHOTO_ID)
    ,CONSTRAINT CLUB_PHOTO_GELLERY_ID_FK FOREIGN KEY(GELLERY_ID)
                REFERENCES CLUB_GALLERY(GELLERY_ID)
);


--○ 동아리 사진첩 관리자 삭제	CLUB_GALLERY_DEL
CREATE TABLE CLUB_GALLERY_DEL (
	BD_ID	    VARCHAR2(20)	
	,DATE	    DATE	        DEFAULT SYSDATE
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
	,REASON_ID	VARCHAR2(20)	NOT NULL
	,GELLERY_ID	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_GALLERY_DEL_BD_ID_PK PRIMARY KEY(BD_ID)
    ,CONSTRAINT CLUB_GALLERY_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT CLUB_GALLERY_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
    ,CONSTRAINT CLUB_GALLERY_DEL_GELLERY_ID_FK FOREIGN KEY(GELLERY_ID)
                REFERENCES CLUB_GALLERY(GELLERY_ID)
);


--○ 컨텐츠신고접수(사진첩)
CREATE TABLE CLUB_GALLERY_REP
( REP_ID	    VARCHAR2(20)	   
, GALLERY_ID	VARCHAR2(20)	    NOT NULL
, REP_DATE	    DATE	        DEFAULT SYSDATE
, CLUBMEM_ID	VARCHAR2(20)	    NOT NULL
, R_REASON_ID	VARCHAR2(20)    	NOT NULL
, PRO_DATE	    DATE	        NULL
, ADMIN_ID	    VARCHAR2(20)	    NULL
, P_REASON_ID	VARCHAR2(20)	    NULL
, CONSTRAINT C_GALLERY_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT C_GALLERY_REP_BC_ID_FK FOREIGN KEY(GALLERY_ID) REFERENCES CLUB_GALLERY(GALLERY_ID)
, CONSTRAINT C_GALLERY_REP_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT C_GALLERY_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(R_REASON_ID)
, CONSTRAINT C_GALLERY_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT C_GALLERY_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(P_REASON_ID)
);


--○ 동아리 사진첩 기타(신고)	CLUB_GALLERY_REP_ETC
CREATE TABLE CLUB_GALLERY_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_GALLERY_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
    ,CONSTRAINT CLUB_GALLERY_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_GALLERY_REP(REP_ID)
);

--○ 동아리 사진첩 기타(처리)	CLUB_GALLERY_PRO_ETC
CREATE TABLE CLUB_GALLERY_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_GALLERY_PRO_ETC_R_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
    ,CONSTRAINT CLUB_GALLERY_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_GALLERY_REP(REP_ID)
);



--정모평가
 
--○ 정모평가관리자삭제	BEE_EVAL_DEL
CREATE TABLE BEE_EVAL_DEL (
	BCD_ID	        VARCHAR2(20)	
	,DATE	        DATE	        DEFAULT SYSDATE
	,ADMIN_ID	    VARCHAR2(20)	NOT NULL
	,REASON_ID	    VARCHAR2(20)	NOT NULL
	,BEE_EVAL_ID	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT BEE_EVAL_DEL_BCD_ID_PK PRIMARY KEY(BCD_ID)
    ,CONSTRAINT BEE_EVAL_DEL_BEE_EVAL_ID_FK FOREIGN KEY(BEE_EVAL_ID)
                REFERENCES BEE_EVAL(BEE_EVAL_ID)
    ,CONSTRAINT BEE_EVAL_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT BEE_EVAL_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
);


--○ 컨텐츠 신고접수(정모평가)
CREATE TABLE BEE_EVAL_REP 
( REP_ID        VARCHAR2(20)    
, BEE_EVAL_ID   VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, CLUBMEM_ID    VARCHAR2(20)    NOT NULL
, R_REASON_ID   VARCHAR2(20)    NOT NULL
, PRO_DATE      DATE            NULL
, ADMIN_ID      VARCHAR2(20)    NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, CONSTRAINT BEE_EVAL_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT BEE_EVAL_REP_BEE_EVAL_ID_FK FOREIGN KEY(BEE_EVAL_ID) REFERENCES BEE_EVAL(BEE_EVAL_ID)
, CONSTRAINT BEE_EVAL_REP_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT BEE_EVAL_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(R_REASON_ID)
, CONSTRAINT BEE_EVAL_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
, CONSTRAINT BEE_EVAL_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(P_REASON_ID)
);

 
 
--○기타 선택 시(신고) 
CREATE TABLE BEE_EVAL_REP_ETC (
	R_ETC_ID	VARCHAR2(20),
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_BEE_EVAL_REP_ETC_R_ETC_ID PRIMARY KEY(R_ETC_ID),
    CONSTRAINT FK_BEE_EVAL_REP_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES BEE_EVAL_REP(REP_ID)   
);

 
--○ 기타 선택 시(처리) 
CREATE TABLE BEE_EVAL_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID  VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT BEE_EVAL_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT BEE_EVAL_PRO_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES BEE_EVAL_REP(REP_ID) 
);
 
 
 
-- 댓글

--○ 동아리게시판 자유글 댓글	CLUB_FREE_B_C
CREATE TABLE CLUB_FREE_B_C (
	BC_ID	    VARCHAR2(20)
	,B_ID	    VARCHAR2(20)	 NOT NULL --게시글 ID
	,CONTENT	VARCHAR2(1000)	 NOT NULL 
	,DATE	    DATE	         DEFAULT SYSDATE
	,CLUBMEM_ID	VARCHAR2(20)	 NOT NULL  -- 작성자
    ,CONSTRAINT CLUB_FREE_B_C_BC_ID_PK PRIMARY KEY (BC_ID)
    ,CONSTRAINT CLUB_FREE_B_C_B_ID_FK FOREIGN KEY(B_ID)
                REFERENCES CLUB_FREE_B(B_ID)
    ,CONSTRAINT CLUB_FREE_B_C_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);


--○ 동아리게시판 자유글 댓글 좋아요 CLUB_FREE_B_C_LIKE
CREATE TABLE CLUB_FREE_B_C_LIKE (
	LIKE_ID	    VARCHAR2(20)	
	,DATE	    DATE	        DEFAULT SYSDATE
	,BC_ID	    VARCHAR2(20)	NOT NULL --댓글 코드
	,CLUBMEM_ID	VARCHAR2(20)	NOT NULL --좋아요 누른 사람
    ,CONSTRAINT CLUB_FREE_B_C_LIKE_LIKE_ID_PK PRIMARY KEY (LIKE_ID)
    ,CONSTRAINT CLUB_FREE_B_C_LIKE_BC_ID_FK FOREIGN KEY(BC_ID)
                REFERENCES CLUB_FREE_B_C(BC_ID)
    ,CONSTRAINT CLUB_FREE_B_C_LIKE_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);


--○ 동아리 자유글 댓글 관리자 삭제	CLUB_FREE_B_C_DEL
CREATE TABLE CLUB_FREE_B_C_DEL (
	BCD_ID	    VARCHAR2(20)	
	,BC_ID	    VARCHAR2(20)	NOT NULL
	,DATE	    DATE	        DEFAULT SYSDATE
	,ADMIN_ID	VARCHAR2(20)	NOT NULL
	,REASON_ID	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_FREE_B_C_DEL_BCD_ID_PK PRIMARY KEY(BCD_ID)
    ,CONSTRAINT CLUB_FREE_B_C_DEL_BC_ID_FK FOREIGN KEY(BC_ID)
                REFERENCES CLUB_FREE_B_C(BC_ID)
    ,CONSTRAINT CLUB_FREE_B_C_DEL_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID)
                REFERENCES ADMIN(ADMIN_ID)
    ,CONSTRAINT CLUB_FREE_B_C_DEL_REASON_ID_FK FOREIGN KEY(REASON_ID)
                REFERENCES DEL_REASON(REASON_ID)
);



--○ 컨텐츠신고접수(동아리-자유글 댓글)
CREATE TABLE CLUB_FREE_B_C_REP 
( REP_ID	    VARCHAR2(20)	
, BC_ID	        VARCHAR2(20)	    NOT NULL
, CLUBMEM_ID	VARCHAR2(20)	    NOT NULL
, REP_DATE	    DATE	        DEFAULT SYSDATE
, R_REASON_ID	VARCHAR2(20)    	NOT NULL
, PRO_DATE	    DATE	        NULL
, ADMIN_ID	    VARCHAR2(20)	    NULL
, P_REASON_ID	VARCHAR2(20)	    NULL
, CONSTRAINT C_F_B_C_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT C_F_B_C_REP_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT C_F_B_C_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(R_REASON_ID)
, CONSTRAINT C_F_B_C_REP_BC_ID_FK FOREIGN KEY(BC_ID) REFERENCES CLUB_FREE_B_C(BC_ID)
, CONSTRAINT C_F_B_C_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(P_REASON_ID)
, CONSTRAINT C_F_B_C_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);


--○ 동아리 자유글 댓글 기타 선택 시(신고)	CLUB_FREE_B_C_REP_ETC
CREATE TABLE CLUB_FREE_B_C_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_FREE_B_C_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
    ,CONSTRAINT CLUB_FREE_B_C_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_FREE_B_C_REP(REP_ID)
);


--○ 동아리-자유글댓글 기타(처리)   
CREATE TABLE CLUB_FREE_B_C_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT CLUB_FREE_B_C_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT CLUB_FREE_B_C_PRO_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES CLUB_FREE_B_C_REP(REP_ID)
);


--○ 동아리게시판 가입인사 댓글 
CREATE TABLE CLUB_INTRO_C (
	BC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(1000)	NOT NULL,
	DATE	DATE	DEFAULT SYSDATE,
	B_ID	VARCHAR2(20)	NOT NULL,
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_C_BC_ID PRIMARY KEY(BC_ID),
    CONSTRAINT FK_CLUB_INTRO_C_B_ID FOREIGN KEY(B_ID) REFERENCES CLUB_INTRO(B_ID),
    CONSTRAINT FK_CLUB_INTRO_C_CLUBMEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
    
);

--○ 동아리게시판 가입인사 댓글 좋아요 
CREATE TABLE CLUB_INTRO_C_LIKE (
	LIKE_ID	VARCHAR2(20)	NOT NULL,
	DATE	DATE	DEFAULT SYSDATE,
	BC_ID	VARCHAR2(20)	NOT NULL,
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_C_LIKE_LIKE_ID PRIMARY KEY(LIKE_ID),
    CONSTRAINT FK_CLUB_INTRO_C_LIKE_BC_ID FOREIGN KEY(BC_ID) REFERENCES CLUB_INTRO_C(BC_ID),
    CONSTRAINT FK_CLUB_INTRO_C_LIKE_CLUMBEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
    
);


--○ 가입인사 댓글 관리자 삭제 
CREATE TABLE CLUB_INTRO_C_DEL (
	BCD_ID	VARCHAR2(20),
	DATE	DATE	DEFAULT SYSDATE,
	ADMIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(20)	NOT NULL,
	BC_ID VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_C_DEL_BCD_ID PRIMARY KEY(BCD_ID),
    CONSTRAINT FK_CLUB_INTRO_C_DEL_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_CLUB_INTRO_C_DEL_REASON_ID FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID),
    CONSTRAINT FK_CLUB_INTRO_C_DEL_BC_ID FOREIGN KEY(BC_ID) REFERENCES CLUB_INTRO_C(BC_ID)
);


--○가입인사 - 댓글 신고 접수   
CREATE TABLE CLUB_INTRO_C_REP (
	REP_ID	VARCHAR2(20)	NOT NULL,
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
	REP_DATE	DATE	DEFAULT SYSDATE,
	R_REASON_ID	VARCHAR2(20)	NOT NULL,
	BC_ID	VARCHAR2(20)	NOT NULL,
	ADMIN_ID	VARCHAR2(20)	NULL,
	P_REASON_ID	VARCHAR2(20)	NULL,
	PRO_DATE	DATE	NULL,
    
    CONSTRAINT PK_CLUB_INTRO_C_REP _REP_ID PRIMARY KEY(REP_ID),
    CONSTRAINT FK_CLUB_INTRO_C_REP _CLUBMEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID),
    CONSTRAINT FK_CLUB_INTRO_C_REP _BC_ID FOREIGN KEY(BC_ID) REFERENCES CLUB_INTRO(BC_ID),
    CONSTRAINT FK_CLUB_INTRO_C_REP _R_REASON_ID FOREIGN KEY(R_REASON_ID) HANDLE_REASON(R_REASON_ID),
    CONSTRAINT FK_CLUB_INTRO_C_REP _ADMIN_ID FOREIGN KEY(ADMIN_ID) ADMIN(ADMIN_ID),
    CONSTRAINT FK_CLUB_INTRO_C_REP _P_REASON_ID FOREIGN KEY(P_REASON_ID) HANDLE_REASON(P_REASON_ID),
);

 
--○ 가입인사 댓글 기타(신고) 
CREATE TABLE CLUB_INTRO_C_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INTRO_C_REP_ETC_R_ETC_ID PRIMARY KEY(R_ETC_ID),
    CONSTRAINT FK_CLUB_INTRO_C_REP_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES CLUB_INTRO_C_REP(REP_ID)
);


--○ 가입인사 댓글 기타(처리) 
CREATE TABLE CLUB_INTRO_C_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	,
	CONTENT	VARCHAR2(500)	NOT NULL,
	REP_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT CLUB_INTRO_C_PRO_ETC_P_ETC_ID PRIMARY KEY(P_ETC_ID),
    CONSTRAINT CLUB_INTRO_C_PRO_ETC_REP_ID FOREIGN KEY(REP_ID) REFERENCES CLUB_INTRO_C_REP(REP_ID) 
);

 
--○ 동아리게시판 문의글
CREATE TABLE CLUB_INQUIRY (
	B_ID	VARCHAR2(20) ,
	MID	VARCHAR2(20)	NOT NULL,
	CID	VARCHAR2(20)	NOT NULL,
	TITLE	VARCHHAR2(100)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	DATE	DATE	DEFAULT SYSDATE,
    
    CONSTRAINT PK_CLUB_INQUIRY_B_ID PRIMARY KEY(B_ID),
    CONSTRAINT FK_CLUB_INQUIRY_MID FOREIGN KEY(MID) REFERENCES MEMBER(MID),
    CONSTRAINT FK_CLUB_INQUIRY_CID FOREIGN KEY(CID) REFERENCES CLUB(CID)
);

 
--○ 동아리게시판 문의글 관리자 삭제 
CREATE TABLE CLUB_INQUIRY_DEL (
	BD_ID	VARCHAR2(20)	,
	DATE	DATE	DEFAULT SYSDATE,
	ADMIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(20)	NOT NULL,
	B_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INQUIRY_DEL_BD_ID PRIMARY KEY(BD_ID),
    CONSTRAINT FK_CLUB_INQUIRY_DEL_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCE ADMIN(ADMIN_ID),
    CONSTRAINT FK_CLUB_INQUIRY_DEL_REASON_ID FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID),
    CONSTRAINT FK_CLUB_INQUIRY_DEL_B_ID FOREIGN KEY(B_ID) REFERENCES CLUB_INQUIRY(B_ID)
    
);

--○ 동아리-문의글 신고 접수  
CREATE TABLE CLUB_INQUIRY_REP (
	REP_ID	VARCHAR2(20)	 ,
	B_ID	VARCHAR2(20)	NOT NULL,
	REP_DATE	DATE	DEFAULT SYSDATE,
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
	R_REASON_ID	VARCHAR2(20)	NOT NULL,
	PRO_DATE	DATE	NULL,
	ADMIN_ID	VARCHAR2(20)	,
	P_REASON_ID	VARCHAR2(20)	,
    
    CONSTRAINT PK_INQUIRY_REP_REP_ID PRIMARY KEY(REP_ID),
    CONSTRAINT FK_INQUIRY_REP_CLUBMEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID),
    CONSTRAINT FK_INQUIRY_REP_B_ID FOREIGN KEY(B_ID) REFERENCES CLUB_INQUIRY(B_ID),
    CONSTRAINT FK_INQUIRY_REP_R_ETC_ID FOREIGN KEY(R_REASON_ID) HANDLE_REASON(R_ETC_ID),
    CONSTRAINT FK_INQUIRY_REP_ADMIN_ID FOREIGN KEY(ADMIN_ID) ADMIN(ADMIN_ID),
    CONSTRAINT FK_INQUIRY_REP_P_ETC_ID FOREIGN KEY(P_REASON_ID) HANDLE_REASON(P_ETC_ID)
);


--○ 문의글 접수 기타(신고)	CLUB_INQUIRY_REP_ETC
CREATE TABLE CLUB_INQUIRY_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_INQUIRY_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
    ,CONSTRAINT CLUB_INQUIRY_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_INQUIRY_REP(REP_ID)
);

--○ 문의글 처리 기타(처리)	CLUB_INQUIRY_PRO_ETC	
CREATE TABLE CLUB_INQUIRY_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_INQUIRY_PRO_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
    ,CONSTRAINT CLUB_INQUIRY_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_INQUIRY_REP(REP_ID)
);


--○ 동아리게시판 문의글 답변 
CREATE TABLE CLUB_INQUIRY_ANS (
	BC_ID	VARCHAR2(20)	,
	CLUBMEM_ID	VARCHAR2(20)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	B_ID	VARCHAR2(20)	NOT NULL,   
    
    CONSTRAINT PK_CLUB_INQUIRY_ANS_BC_ID PRIMARY KEY(CLUB_INQUIRY_ANS_BC_ID),
    CONSTRAINT FK_CLUB_INQUIRY_ANS_CLUBMEM_ID FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID),
    CONSTRAINT FK_CLUB_INQUIRY_ANS_B_ID FOREIGN KEY(B_ID) REFERENCES CLUB_INQUIRY(B_ID)
);


--○ 동아리 문의답변 관리자 삭제  
CREATE TABLE CLUB_INQUIRY_ANS_DEL (
	BCD_ID	VARCHAR2(20)    ,
	DATE	DATE	DEFAULT SYSDATE,
	ADMIN_ID	VARCHAR2(20)	NOT NULL,
	REASON_ID	VARCHAR2(20)	NOT NULL,
	BC_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_CLUB_INQUIRY_ANS_DEL_BCD_ID PRIMARY KEY(BCD_ID),
    CONSTRAINT FK_CLUB_INQUIRY_ANS_DEL_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_CLUB_INQUIRY_ANS_DEL_REASON_ID FOREIGN KEY(REASON_ID) REFERENCES DEL_REASON(REASON_ID),
    CONSTRAINT FK_CLUB_INQUIRY_ANS_DEL_BC_ID FOREIGN KEY(BC_ID) REFERENCES CLUB_INQUIRY_ANS(BC_ID)
);


--○ 컨텐츠신고접수(동아리-문의글 답변)
CREATE TABLE CLUB_INQUIRY_ANS_REP 
( REP_ID        VARCHAR2(20)  
, CLUBMEM_ID    VARCHAR2(20)    NOT NULL
, REP_DATE      DATE            DEFAULT SYSDATE
, R_REASON_ID   VARCHAR2(20)    NOT NULL
, BC_ID         VARCHAR2(20)    NOT NULL
, PRO_DATE      DATE            NULL
, ADMIN_ID      VARCHAR2(20)    NULL
, P_REASON_ID   VARCHAR2(20)    NULL
, CONSTRAINT C_I_ANS_REP_REP_ID_PK PRIMARY KEY(REP_ID)
, CONSTRAINT C_I_ANS_REP_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT C_I_ANS_REP_REASON_ID_FK FOREIGN KEY(R_REASON_ID) REFERENCES HANDLE_REASON(R_REASON_ID)
, CONSTRAINT C_I_ANS_REP_BC_ID_FK FOREIGN KEY(BC_ID) REFERENCES CLUB_INQUIRY_ANS(BC_ID)
, CONSTRAINT C_I_ANS_REP_P_REASON_ID_FK FOREIGN KEY(P_REASON_ID) REFERENCES HANDLE_REASON(P_REASON_ID)
, CONSTRAINT BEE_REP_ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);


--○ 동아리 문의글 답변 기타 (신고)	CLUB_INQUIRY_ANS_REP_ETC
CREATE TABLE CLUB_INQUIRY_ANS_REP_ETC (
	R_ETC_ID	VARCHAR2(20)	
	,CONTENT	VARCHAR2(500)	NOT NULL
	,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_INQUIRY_ANS_REP_ETC_R_ETC_ID_PK PRIMARY KEY(R_ETC_ID)
    ,CONSTRAINT CLUB_INQUIRY_ANS_REP_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_INQUIRY_ANS_REP(REP_ID)
);

--○ 문의글 답변 신고 기타(처리)	CLUB_INQUIRY_ANS_PRO_ETC
CREATE TABLE CLUB_INQUIRY_ANS_PRO_ETC (
	P_ETC_ID	VARCHAR2(20)	
	,CONTENT 	VARCHAR2(500)	NOT NULL
    ,REP_ID	    VARCHAR2(20)	NOT NULL
    ,CONSTRAINT CLUB_INQUIRY_ANS_PRO_ETC_P_ETC_ID_PK PRIMARY KEY(P_ETC_ID)
    ,CONSTRAINT CLUB_INQUIRY_ANS_PRO_ETC_REP_ID_FK FOREIGN KEY(REP_ID)
                REFERENCES CLUB_INQUIRY_ANS_REP(REP_ID)
);


----------------------------------------------------------------------------------
--● 회계 테이블

--○ 수입 분류	INCOME_TYPE	
CREATE TABLE INCOME_TYPE (
	TYPE_ID	VARCHAR2(20)	
	,TYPE	VARCHAR2(20)	NOT NULL
    ,CONSTRAINT INCOME_TYPE_TYPE_ID_PK PRIMARY KEY(TYPE_ID)
);

--○ 지출 분류
CREATE TABLE EXPENSE_TYPE 
( TYPE_ID   VARCHAR2(20)    	NOT NULL
, TYPE      VARCHAR2(40)    NOT	NULL
, CONSTRAINT EXPENSE_TYPE_TYPE_ID_PK PRIMARY KEY(TYPE_ID)
);


--○ 지출세부내역	
CREATE TABLE EXPENSE_TYPE_D 
( TYPE_D_ID VARCHAR2(20)    	
, TYPE      VARCHAR2(40)    NOT	NULL
, TYPE_ID   VARCHAR2(20)    	NOT NULL
, CONSTRAINT EXPENSE_TYPE_D_TYPE_D_ID_PK PRIMARY KEY(TYPE_D_ID)
, CONSTRAINT EXPENSE_TYPE_D_TYPE_ID_FK FOREIGN KEY(TYPE_ID)
             REFERENCES EXPENSE_TYPE(TYPE_ID)
);

--○ 카드 등록 
CREATE TABLE CARD 
( CARD_ID           VARCHAR2(20)   
, ACCOUNT_ID        VARCHAR2(20)       NOT NULL
, NAME              VARCHAR2(50)       NOT NULL
, CONSTRAINT CARD_CARD_ID_PK PRIMARY KEY(CARD_ID)
, CONSTRAINT CARD_ACCOUNT_ID_FK FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

--○ 계좌등록 
CREATE TABLE ACCOUNT (
	ACCOUNT_ID	VARCHAR2(20),
	NAME	    VARCHAR2(20) NOT NULL,
	NUM         VARCHAR2(100) NOT NULL,
	CLUBMEM_ID	    VARCHAR2(20)	NOT NULL,
	INIT    	NUMBER	DEFAULT 0,
    
    CONSTRAINT PK_ACCOUNT_ACCOUNT_ID PRIMARY KEY(ACCOUNT_ID)
    ,CONSTRAINT ACCOUNT_CLUBMEM_ID_FK PRIMARY KEY(CLUBMEM_ID)
                REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
    
);

--○ 회계부 지출
CREATE TABLE EXPENSE 
( EXPENSE_ID    VARCHAR2(20)    
, PRICE         NUMBER          DEFAULT 0
, EXPENSE_DATE  DATE            NOT NULL
, TYPE_D_ID     VARCHAR2(20)    NOT NULL
, CONTENT       VARCHAR2(50)    NULL
, DATE          DATE            DEFAULT SYSDATE
, CLUBMEM_ID    VARCHAR2(20)    NOT NULL
, CONSTRAINT EXPENSE_EXPENSE_ID_PK PRIMARY KEY(EXPENSE_ID)
, CONSTRAINT EXPENSE_TYPE_D_ID_FK FOREIGN KEY(TYPE_D_ID) REFERENCES EXPENSE_TYPE_D(TYPE_D_ID)
, CONSTRAINT EXPENSE_CLUBMEM_ID_FK FOREIGN KEY(CLUBMEM_ID) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
);


--○ 회계부 수입
CREATE TABLE INCOME 
( INCOME_ID     VARCHAR2(20)  
, PRICE         NUMBER          DEFAULT 0
, INCOME_DATE   DATE            NULL                -- 입금 일자
, PAYER         VARCHAR2(20)    NOT NULL            -- 입금자
, TYPE_ID       VARCHAR2(20)    NOT NULL            -- 수입 분류 코드
, CONTENT       VARCHAR2(50)    NULL
, DATE          DATE            DEFAULT SYSDATE     -- 작성일
, CLUBMEM_ID    VARCHAR2(20)    NOT NULL            -- 작성자
, ACCOUNT_ID    VARCHAR2(20)    NOT NULL
, CONSTRAINT INCOME_INCOME_ID_PK PRIMARY KEY(INCOME_ID)
, CONSTRAINT INCOME_PAYER_FK FOREIGN KEY(PAYER) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT INCOME_TYPE_ID_FK FOREIGN KEY(TYPE_ID) REFERENCES INCOME_TYPE(TYPE_ID)
, CONSTRAINT INCOME_CLUBMEM_ID_FK FOREIGN KEY(PAYER) REFERENCES CLUBMEMBERLIST(CLUBMEM_ID)
, CONSTRAINT INCOME_ACCOUNT_ID_FK FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);


--○ 카드 지출
CREATE TABLE EXPENSE_CARD
( EX_CARD_ID    VARCHAR2(20)	
, CARD_ID       VARCHAR2(20)	    NOT NULL
, EXPENSE_ID	VARCHAR2(20)	    NOT NULL
, CONSTRAINT EXPENSE_CARD_EX_CARD_ID_PK PRIMARY KEY(EX_CARD_ID)
, CONSTRAINT EXPENSE_CARD_CARD_ID_FK FOREIGN KEY(CARD_ID) REFERENCES CARD(CARD_ID)
);


-- 계좌이체 지출 40 
CREATE TABLE EXPENSE_ACCOUNT (
	EX_ACCOUNT_ID	VARCHAR2(20)	,
	ACCOUNT_ID	VARCHAR2(20)	NOT NULL,
	EXPENSE_ID	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT PK_EXPENSE_ACCOUNT_EX_ACCOUNT_ID PRIMARY KEY(EX_ACCOUNT_ID),
    CONSTRAINT FK_EXPENSE_ACCOUNT_ACCOUNT_ID FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_EXPENSE_ACCOUNT_EXPENSE_ID FOREIGN KEY(EXPENSE_ID) REFERENCES EXPENSE(EXPENSE_ID)
);



--○ 회비 납부
CREATE TABLE FEE
( FEE_ID            VARCHAR2(20)	
, INCOME_ID         VARCHAR2(20)	    NOT NULL
, FEEYEAR	        VARCHAR2(20)	    NOT NULL
, FEEMONTH          VARCHAR2(20)	    NOT NULL
, CONSTRAINT FEE_FEE_ID_PK PRIMARY KEY(FEE_ID)
, CONSTRAINT FEE_INCOME_ID_FK FOREIGN KEY(INCOME_ID) REFERENCES INCOME(INCOME_ID)
);




